### ISSUE TITLE
Explore use of BRPOPLPUSH / RPOPLPUSH to provide at most once delivery guarantee

### ISSUE THREAD

**Issue by akira** [akira/exq#106]
See http://redis.io/commands/rpoplpush or http://redis.io/commands/brpoplpush for more info.

For BRPOPLPUSH, would need to split out fetching to a per queue process as only 1 queue is supported.

**Comment by akira** [comment]
Implemented by #130

**Comment by nitzanav** [comment]
Any way that BRPOPLPUSH will be supported for better performance? :)

**Comment by akira** [comment]
I don't believe BRPOPLPUSH supports multiple destinations:

https://github.com/antirez/redis/issues/2030
