### ISSUE TITLE
Link to toniq?

### ISSUE THREAD

**Issue by joakimk** [akira/exq#110]
Hello

I'm the creator and maintainer of [toniq](https://github.com/joakimk/toniq), a native Elixir background job library. By being native the library can use erlang serialization rather than the resque/sidekiq format which has some benefits (like not loosing type information).

I have however always had a link to this project in my project readme as a recommendation in case resque/sidekiq compatibility is a requirement.

I was just wondering if you would consider to do the same in reverse?

Something like: `"If you don't need resque/sidekiq compatibility, you could also look at [toniq](https://github.com/joakimk/toniq) which uses erlang serialization instead of JSON. You can run both Exq and Toniq in the same app for different workers."`

Just a long shot. You can of course say no.

Happy hacking :)

**Comment by akira** [comment]
Hi,

Joakim, sure would love to!   I'll write something up in the README.

**Comment by akira** [comment]
Link added

**Comment by joakimk** [comment]
Thank you! :)
