### ISSUE TITLE
Create example app demonstrating Sidekiq and/or Resque and Exq communication

### ISSUE THREAD

**Issue by akira** [akira/exq#112]
An example app that will have an example of a ruby app offloading jobs to an Elixir Exq app.

**Comment by sineed** [comment]
@akira I've made demo app illustrating communication between SIdekiq and Exq:

https://github.com/sineed/exq_sidekiq_demo_app

Please have a look.

**Comment by akira** [comment]
:+1: looks great! Will add it to the documentation!

**Comment by akira** [comment]
Added to docs.  Thanks!
