### ISSUE TITLE
Bump uuid to `>=1.1.1`

### ISSUE THREAD

**Issue by gogogarrett** [akira/exq#126]
I'm currently trying to integrate [guardian](https://github.com/hassox/guardian) 0.8.0 into an elixir app that is using exq v0.4.3 and I am running into issues where exq is depending on uuid `1.0.0`.

Is there anyway we can get this bumped?

```
λ mix deps.get                                                                                                 2.1.2 feature/a-a-assignments a48dd8c ✗
Running dependency resolution
Looking up alternatives for conflicting requirements on uuid
  Activated version: 1.1.1
  From exq v0.4.3: ~> 1.0.0
  From guardian v0.8.0: >=1.1.1

** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies
```

**Comment by akira** [comment]
Just published v0.4.4, I relaxed the deps and tested with guardian v0.8.0

**Comment by gogogarrett** [comment]
Thanks a lot for that, especially in the timely manner!

**Comment by akira** [comment]
No problem!  Let me know if you run into any other issues.

**Comment by fishtreesugar** [comment]
LGTM
I meet the same issue when I use guardian, but my [fork](https://github.com/fishtreesugar/exq/commits/master) go far away

**Comment by akira** [comment]
@fishtreesugar Redix support, that's great!  Would love to have a PR for that when it's ready :fire:
