### ISSUE TITLE
Confused By UI Plug Usage

### ISSUE THREAD

**Issue by jcsmith1859** [akira/exq#127]
Greetings,

I am currently running a phoenix app inside of a docker container, and am having a bit of an issue using `Exq.RouterPlug` to forward a request prefixed with `"/exq"` to the plug. The closest that I have gotten is to serve up the static index page with all of the assets throwing a 404.

I am new to elixir and new to phoenix, so any guidance or clarification would be well appreciated.

```elixir
  scope "/exq" do
    pipe_through :browser

    forward "/", Exq.RouterPlug.Router, :index
  end
```

**Comment by jcsmith1859** [comment]
So I finally figured it out:

```elixir
...
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    # note that you need to remove the :protect_from_forgery plug and place it inside its own pipeline
    plug Exq.RouterPlug, namespace: "exq"
  end

  pipeline :csrf do
    plug :protect_from_forgery
  end

...
  scope "/", MyApp do
    pipe_through :browser

    forward "/exq", Exq.RouterPlug.Router, :index
  end
```

Figured I would shared this in case someone else was having the same issues as me

**Comment by j-mcnally** [comment]
Thanks it looks like some upstream things about the way pipelines are setup
have changed. Thanks for the fix. I'll see if we need to make any mods or
if this is mostly docs.

On Thursday, December 17, 2015, Jared <notifications@github.com> wrote:

> So I finally figured it out:
>
> ...
>   pipeline :browser do
>     plug :accepts, ["html"]
>     plug :fetch_session
>     plug :fetch_flash
>     plug :put_secure_browser_headers    # note that you need to remove the :protect_from_forgery plug and place it inside its own pipeline
>     plug Exq.RouterPlug, namespace: "exq"
>   end
>
>   pipeline :csrf do
>     plug :protect_from_forgery
>   end
> ...
>   scope "/", MyApp do
>     pipe_through :browser
>
>     forward "/exq", Exq.RouterPlug.Router, :index
>   end
>
> Figured I would shared this in case someone else was having the same
> issues as me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akira/exq/issues/127#issuecomment-165505944>.
>


-- 

<http://www.kohactive.com>
Justin McNally
Technology Director / Principal
p: 312.273.3074 <+13122733074> | e: justin@kohactive.com | skype:
justinmcnally211 <http://is.gd/UuXAGG>
  <https://github.com/j-mcnally>  <https://twitter.com/j_mcnally>
<https://www.linkedin.com/profile/view?id=143776726>
