### ISSUE TITLE
Redis Pool

### ISSUE THREAD

**Issue by benwilson512** [akira/exq#128]
Hey!

In looking through the code it appears that all of the genservers started by https://github.com/akira/exq/blob/master/lib/exq/manager/server.ex share a single redis connection.

Have you considered setting up :eredis with poolboy so that the different processes aren't bottlenecked by this single connection?

This would also go a long way towards letting you start the supervisors started in Exq.Manager.Server.init cleanly as children of the manager supervisor instead of directly inside the GenServer init.

Thanks!
- Ben

**Comment by akira** [comment]
:+1: for using a Redis connection pool via poolboy.  Would help with #129 as well as you mentioned.

**Comment by olivermt** [comment]
fishcakez_ on freelang (creator of Connection etc) did a lot of benchmarking against localhost and got 30% less latency with poolboy than just a straight up shared connection.

This kind of makes as the server side of redis is single threaded so you dont really gain anything except adding the poolboy overhead into the loop.

I was the one who PR'd the poolboy stuff to the redix readme.md and this discussion didn't come up until right after that, so I don't know if something has changed.

A simple supervisor that brings Redix back up should probably be all you need anyways.
Yay for less dependencies and less setup code.

**Comment by akira** [comment]
@olivermt do you have a link to this discussion?
