### ISSUE TITLE
Redis Backend Support

### ISSUE THREAD

**Issue by fishtreesugar** [akira/exq#137]
As mention [previoursly](https://github.com/akira/exq/issues/126) ,  my colleague @zhongwencool add the [supporting of Redix](https://github.com/zhongwencool/exq/commit/1db65540d08f684b4cd7ba94d9a4455530d875c5)
and he implement  a [cluster wrapper for Redix](https://github.com/zhongwencool/redix-cluster) too!

My question is what is a better way to add redix to exq? use an adapter of redis or replace eredis by redix?

**Comment by akira** [comment]
Hi @fishtreesugar,

Thanks!  Is it possible to tie in Redix with using connection pool (#128)? The adapter is a nice to have, however I think for me the pool would be higher priority if we are already switching to Redix (similar to https://github.com/whatyouhide/redix#using-redix-in-the-real-world).

**Comment by akira** [comment]
Provided by #136
