### ISSUE TITLE
Can't connect to ElastiCache

### ISSUE THREAD

**Issue by darksheik** [akira/exq#142]
I don't know if I have a specific issue, just not sure where to go for help.
I have exq running excellently on my development machine which is running a local instance of Redis.

In production, I would like to run the app on an EC2 instance while running Redis on ElastiCache.  I opened port 6379 on ElastiCache and I'm able to connect with ```redis-cli``` no problem from the EC2 command line.

I'm seeing the below message when trying to use exq.  I've double-checked my hostname for ElastiCache in my prod config and it's fine.  I'm wondering if perhaps another port needs to be open on one of these two machines or if there's another reason why I might see this message?  Or any other tips for troubleshooting the connection?

```
ubuntu@ip-000-00-0-000:~/workspace/my_app$ MIX_ENV=prod mix exq.run
** (EXIT from #PID<0.47.0>) shutdown: failed to start child: Exq.Manager.Server
    ** (EXIT) {:connection_error, {:connection_error, :econnrefused}}
```

**Comment by akira** [comment]
Sorry about that, it seems like the mix task was out of date with the configs. I updated the mix task - it is basically using mix run --no-halt which you can just use instead:

```
 MIX_ENV=prod mix run --no-halt
```

**Comment by darksheik** [comment]
I am running Exq inside a Phoenix app.  Looks like the Redis connection is working.  I can do this:

```
iex(3)> Exq.Enqueuer.Server.list_queues(redis, "my_app")
["default"]
```

When I try to enqueue a job, though, I get "no process":
```
iex(4)> Exq.enqueue(:exq, "default", MyApp.Workers.WorkerName, [20])          
** (exit) exited in: GenServer.call(:exq, {:enqueue, "default", MyApp.Workers.WorkerName, [20]}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:544: GenServer.call/3
```

This didn't happen in development -- worked right out of the box.
Also, it's a different repo, but ```MIX_ENV=prod mix exq.ui``` is just attempting to connect to localhost despite my prod settings.

**Comment by darksheik** [comment]
I can also manually enqueue jobs:

```
iex(13)> Exq.Redis.JobQueue.enqueue(redis, "my_app", "default", MyApp.Workers.WorkerName, [20])
{:ok, "4a66ec9a-fea6-4539-bc20-8ecc00275d30"}
```

**Comment by akira** [comment]
What version are you running? 
Note that the latest version (0.5), we had changed the module name to be "Exq" instead of ":exq".  Can you try this?
```
Exq.enqueue(Exq, "default", MyApp.Workers.WorkerName, [20])  
```

The mix task definitely had a bug in it where it was not picking up any settings from the "config.exs" file.  I fixed that, but that is still only on master - I haven't released it yet on hex.pm, as there's something else I wanted to fix before that and hadn't gotten to b/c of the holidays. 

The fixed mix task now basically just does this, can you try:

```
MIX_ENV=prod mix run --no-halt
```

**Comment by darksheik** [comment]
Yup, that did it (```:exq to Exq```).  I recently bumped the version.  Also think I started living on the edge a bit when I forked the master branch and used it to debug.  I think I can figure it out from here.  Thanks for the help!

**Comment by akira** [comment]
@darksheik great, glad it works!  Can I close issue?

**Comment by darksheik** [comment]
Yup!  I'll just point to master til next release.  Thanks!
