### ISSUE TITLE
Job introspection from worker

### ISSUE THREAD

**Issue by akira** [akira/exq#155]
Ability for worker to retrieve it's job metadata (for example, jid, retry count)

Perhaps support for this in worker:

```
 (job = %Job{}, param1, param2..)
```

Preferably, just provide an api like (suggested by edgurgel):

```
Exq.Jobs.mine(self) 
```

That would retrieve that data so that we don't have to change or provide multiple signatures for `perform` since this may not be as commonly used.

Suggested by olivermt on elixir-lang slack.

**Comment by olivermt** [comment]
What is the discussion needed here?

I am making a system that does time delayed retries of dialing out if target is busy for some video conferencing stuff.

Just being able to slap it in an Exq queue and inspect the job to figure out when to give up etc would be awesome!

Of course I can keep the job info in the DB as well, but its a bit overkill as the functionality is considered ephemral anyways.

**Comment by akira** [comment]
@olivermt I agree that the feature itself is needed.  I only added the "needs discussion" for the implementation detail - ie how to provide this API in a clean way from the worker. 

Initially was wondering if we can just store this info in the spawned process or the worker state and avoid having any sort of registry, but not sure if there's a clean way to do that  (the worker itself is busy executing so can't respond to messages from it's pid, and not sure if there's a clean way of getting the supervisor process from the worker pid).

**Comment by olivermt** [comment]
I suggest we make an ets table from the worker spawner / supervisor and simply store the worker data using the worker pid as a key.

That way you get a clean api that you can call on (self) and you get a very clean and lightweight configuration scenario.

1. Only make the ets table if you have `metadata: true` in exq config
2. Worker spawner creates data on pid creation
3. worker spawner deletes data when worker is done doing work
4. If config is not present, performance and behavior is identical as it is today

**Comment by akira** [comment]
That would work, we can add an additional middleware chain to handle this.  

I'm wondering if at this point the `spawn_link` should be changed to a GenServer.  Either way, would have to add a `receive` to wait for a message before doing the work so we can associate the `pid` of the module worker (adding receive before https://github.com/akira/exq/blob/master/lib/exq/worker/server.ex#L115).

**Comment by ananthakumaran** [comment]
Any conclusion on this case?

We need to track the status(working/done/failed) of the job in mysql. This looks like an ideal case for a custom middleware. But the main problem is, if middleware throws error for any reason the `Exq.Worker.Server` exits and leaves the job in limbo state. But the bigger problem is, the worker_count in `Exq.Manager.Server` is not decremented and after enough errors, the whole queue stops working (we learned it the hard way).

I could provide a PR if there is an agreement about the API.

**Comment by akira** [comment]
Yes, I think this is needed, I am backlogged and haven't had time to implement this. 

For the API, something like this would work: 

`Exq.worker_job()` 

Also, anything to make middleware more resilient to this could help.  If you can provide a PR I can definitely take a look and help out.  Thanks!
