### ISSUE TITLE
Error when upgrading to 0.6.4

### ISSUE THREAD

**Issue by martinstannard** [akira/exq#174]
I just bumped the version of exq from 0.4.2 to 0.6.4 and now the app won't start:

```
Consolidated Poison.Decoder
Consolidated List.Chars
Consolidated Poison.Encoder
Consolidated Ecto.Queryable
Consolidated Collectable
Consolidated Enumerable
Consolidated String.Chars
Consolidated IEx.Info
Consolidated Inspect

=INFO REPORT==== 9-Feb-2016::09:36:05 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application eredis: could not find application file: eredis.app
```

I did a `mix deps.get` then `iex -S mix`

Thoughts?

**Comment by akira** [comment]
The Redis driver was changed to [Redix](https://github.com/whatyouhide/redix).  Is `:eredis` still on the application list?

**Comment by akira** [comment]
@martinstannard were you able to see if there's any references to :eredis in any of your app?

**Comment by martinstannard** [comment]
Yes, that was the issue @akira. I've removed the reference to :eredis and the app works fine now. Feel free to close.

**Comment by akira** [comment]
Great, thanks for the follow up!
