### ISSUE TITLE
enqueued_at is recorded as milliseconds instead of seconds

### ISSUE THREAD

**Issue by DavidAntaramian** [akira/exq#182]
I'm trying to figure out if this is an intentional discrepancy, since I can't find any issues discussing it:

Sidekiq expects the `enqueued_at` value to be a [Float of _seconds_ since the Unix epoch](https://github.com/mperham/sidekiq/blob/v4.1.1/lib/sidekiq/client.rb#L186-L190) (in Ruby: `Time.now.to_f`), but Exq serializes jobs to the queue with `enqueued_at` as the [Integer _milliseconds_ since the Unix epoch](https://github.com/akira/exq/blob/master/lib/exq/redis/job_queue.ex#L264). Unfortunately, this throws Sidekiq's reporting functionality off—when Exq is the last to add a job to the queue before stats are generated, the default queue's latency goes from a few seconds to some 40,000 years ahead of schedule.

**Comment by akira** [comment]
Thanks for reporting, will have to investigate. I've tried the Sidekiq UI in the past along with Exq, but probably missed that.

**Comment by akira** [comment]
Fixed by #173
