### ISSUE TITLE
Update a job

### ISSUE THREAD

**Issue by pdilyard** [akira/exq#185]
Is there a way I can update a job by it's ID? For example, I have a job that is scheduled to run at 8:00AM tomorrow morning, but later I might need to be able to change it to run at 9:00AM instead. Is there a way this can be done (even by deleting the job entirely and creating a new one)?

**Comment by akira** [comment]
There's an API to find the job, but there's not one to remove a job at the moment. 

However, I'm working on adding a bunch of new API methods, so I can certainly take a look at adding that as well.

**Comment by pdilyard** [comment]
That'd be great, this feature is definitely something I'll want soon

**Comment by almassapargali** [comment]
Yeah, I'm having exact this scenario where I need to reschedule scheduled job. On ruby/sidekiq I could find job by id, and then remove it. Could you give this one a little priority please? (I'd help myself, but not much familiar with Redis and Sidekiq internals).

**Comment by akira** [comment]
@almassapargali @pdilyard I have a branch, PR #173 that provides some of this. This should be working. However, it is not yet compatible with the UI, so I still have to do that part. 

However, take a look and see if that works for you guys. See https://github.com/akira/exq/blob/api_cleanup/lib/exq/api.ex

So you can call `remove_job` or `remove_scheduled` using this API.

**Comment by pdilyard** [comment]
Looks perfect. I'd just persist the job ID in my database. I'd love to see this get merged soon! 

❤️ 💛 💙

**Comment by akira** [comment]
@pdilyard It's been merged.  :shipit:

**Comment by almassapargali** [comment]
Thanks for fast responses and for the library at all!

**Comment by akira** [comment]
:+1: :+1:

**Comment by pdilyard** [comment]
@akira How would I actually make the call to `remove_job`? I've tried the following:

```
iex> Exq.Api.remove_job(Exq, "queue", "job-id")
# no function clause handle_call/3  {:remove_job, "queue", "job-id"}
iex> Exq.Api.remove_job(Exq.Api, "queue", "job-id")
# no process
```

**Comment by pdilyard** [comment]
Just to clarify for anyone that finds this issue, you'll want to call these functions like this:

```elixir
Exq.Api.remove_job(Exq.Api, "queue_name", "job-id")
# or
Exq.Api.remove_scheduled(Exq.Api, "job-id")
```

**Comment by akira** [comment]
@pdilyard thanks! That's probably a good thing to put on the README as an "API" section.
