### ISSUE TITLE
Exq shuts down when losing redis connection

### ISSUE THREAD

**Issue by rranelli** [akira/exq#186]
I'm very interested in using `Exq` in production but I found the two following
issues:

  - The application won't start if Redis is down. I understand the reasons not
    to allow `Exq` to start if Redis is unavailable, but since `Exq` won't
    play a *vital* part of my system, I would rather have `Exq` up and handle
    all `enqueue` errors myself. I think this behavior should be `opt-in`.
    What do you guys think??

  - **After** the application has started, if it loses connection with Redis
    the application will shut down too. If I understood correctly the
    discussion @ #136, this wasn't supposed to happen. If Redis gets back
    online, `Exq` is not restarted:

```
13:32:26.903 [error] GenServer Exq.Redis.Client terminating
** (stop) :econnrefused
Last message: nil
State: %{opts: [socket_opts: [], backoff: nil, host: "127.0.0.1", port: 6379, database: nil, password: nil], receiver: nil, reconnection_attempts: 0, socket: nil, tail: ""}
13:32:26.903 [error] GenServer Exq.Scheduler terminating
** (stop) exited in: :gen_server.call(Exq.Redis.Client, {:commands, [["ZRANGEBYSCORE", "exq:schedule", 0, "1461861146.880515"], ["ZRANGEBYSCORE", "exq:retry", 0, "1461861146
.880515"]]}, 5000)
    ** (EXIT) :econnrefused
    (stdlib) gen_server.erl:212: :gen_server.call/3
    (exq) lib/exq/redis/job_queue.ex:136: Exq.Redis.JobQueue.scheduler_dequeue/3
    (exq) lib/exq/scheduler/server.ex:68: Exq.Scheduler.Server.dequeue/1
    (exq) lib/exq/scheduler/server.ex:56: Exq.Scheduler.Server.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :start_timeout}
State: %Exq.Scheduler.Server.State{namespace: "exq", queues: ["default"], redis: Exq.Redis.Client, scheduler_poll_timeout: 200}
13:32:26.903 [info] Application exq exited: shutdown
```

**Comment by rranelli** [comment]
I ended up removing `:exq` from the `application` function in `mix.exs` and wrote the following "wrapper": https://gist.github.com/rranelli/7dc10a4ab6dca12e74c469274303966e

Is this solution ok ?

**Comment by akira** [comment]
* As fas as the "fail fast" behavior when starting Exq with Redis down, that is the intended behavior currently and how most of the other Redis based queueing systems work as well. 

* For deploying the app, for example with `exrm`,  you would need to have `:exq` in the application list for it to properly pick up dependencies.  I can see there being added a config flag for Exq on whether to start Exq on startup. With this, it can be set to 'false' and let you control the initialization of it.  However, I'm not sure how you are plugging in your wrapper, but I would be careful to make sure it is supervised and properly plugs in to the application supervision hierarchy, I don't think the way you have it does that?  

* For Exq shutting down after it is already running when Redis is shutdown, that is an issue, and I need to take a look at that one. 





I will take a look

**Comment by rranelli** [comment]
My supervision tree looks like this:

![screenshot from 2016-05-01 12 15 42](https://cloud.githubusercontent.com/assets/4231743/14942557/765cca66-0f96-11e6-8319-4c131cf1da29.png)

(with AsyncQueue being supervised by my apps' root supervisor).

**Comment by akira** [comment]
Yeah, that's what I mean, but you kill "Elixir.AsyncQueue" then it would get restarted in this case?  You can try to do that through the observer UI. The idea is that the process should be supervised, so if you kill it, it should restart the process automatically.

**Comment by rranelli** [comment]
oh yes, I did that test and the process is restarted just fine =)

**Comment by akira** [comment]
@rranelli what version of Redix are you using for Exq?  I can't replicate issue with Redis going down after Exq has already come up.  I tried both running the tests (we have tests tagged "failure_scenarios"), and also manually shutting down Redis after starting Exq.  I am only seeing:

```
2016-05-10 22:26:18.445 [error]: Error connecting to Redis (127.0.0.1:6555): connection refused

2016-05-10 22:26:18.446 [error]: Disconnected from Redis (127.0.0.1:6555): :tcp_closed

2016-05-10 22:26:18.446 [error]: Disconnected from Redis (127.0.0.1:6555): :tcp_closed

2016-05-10 22:26:18.446 [error]: Error connecting to Redis (127.0.0.1:6555): connection refused

2016-05-10 22:26:18.446 [error]: Error connecting to Redis (127.0.0.1:6555): connection refused
```

But there is no crash.  Do you have steps to reproduce this?

**Comment by rranelli** [comment]
What I did was manually shutting down Redis after starting Exq. Nothing special about it.

The my `redix` and `exq` entries in my `mix.lock` are:

```
"redix": {:hex, :redix, "0.3.4"},
"exq": {:hex, :exq, "0.7.0"},
```

**Comment by rranelli** [comment]
I tried updating Redix and re-running the tests and the behavior is the same.
The full output is here https://gist.github.com/2c7db726879e04de6cf1880f5ee064e3

**Comment by akira** [comment]
OK.  Finally able to reproduce it 😄  

The issue is that the `reconnect_on_sleep` option was not set by default. I will add it to the default config.  

For now, you can set this in your config file:
```
config :exq,
  reconnect_on_sleep: 100
```

**Comment by mtarnovan** [comment]
Had the same issue, that fixes it for me. Thanks
