### ISSUE TITLE
Reloading config

### ISSUE THREAD

**Issue by RobinClowers** [akira/exq#190]
We are using exrm to deploy our app, and when I added middleware, it didn't take until I stopped and started my app. Is there a way I can reload config on the fly? If not, what's the correct way to gracefully stop workers and restart exq?

**Comment by aaronjensen** [comment]
Looks like `Exq.config_change/3` would be the proper way to handle this

**Comment by RobinClowers** [comment]
Where do you see that?

**Comment by aaronjensen** [comment]
http://erlang.org/doc/man/application.html#Module:config_change-3
