### ISSUE TITLE
Timex

### ISSUE THREAD

**Issue by merqlove** [akira/exq#201]
Must be in the deps of mix.exs
```elixir
[{:timex, "~> 2.0"}]
```

Otherwise:
```elixir
warning: function Time.now/0 is undefined or private
Found at 2 locations:
  lib/exq/middleware/logger.ex:11
  lib/exq/middleware/logger.ex:27

warning: function Time.diff/3 is undefined or private
  lib/exq/middleware/logger.ex:27

warning: function Time.now/0 is undefined or private
Found at 4 locations:
  lib/exq/redis/job_queue.ex:60
  lib/exq/redis/job_queue.ex:131
  lib/exq/redis/job_queue.ex:228
  lib/exq/redis/job_queue.ex:238

warning: function Time.add/2 is undefined or private
Found at 2 locations:
  lib/exq/redis/job_queue.ex:60
  lib/exq/redis/job_queue.ex:228

warning: function Time.from/2 is undefined or private
Found at 2 locations:
  lib/exq/redis/job_queue.ex:60
  lib/exq/redis/job_queue.ex:228

warning: function Time.to_seconds/1 is undefined or private
  lib/exq/redis/job_queue.ex:201

warning: function DateTime.universal/0 is undefined or private
Found at 2 locations:
  lib/exq/redis/job_queue.ex:221
  lib/exq/redis/job_queue.ex:234

warning: function Timex.Time.now/1 is undefined or private
  lib/exq/redis/job_queue.ex:357

warning: function DateTime.universal/0 is undefined or private
Found at 2 locations:
  lib/exq/redis/job_stat.ex:17
  lib/exq/redis/job_stat.ex:29

warning: function DateTime.universal/0 is undefined or private
  lib/exq/stats/server.ex:31
```

**Comment by goofansu** [comment]
Having this problem with latest 0.7.2.

**Comment by akira** [comment]
@goofansu @merqlove OK will send out an update for this and do a minor version bump with that change. 

FYI the latest in master is Elixir 1.3 only and has no Timex dependencies, so when that rolls out this will no longer apply (Latest Timex version 3 only works on Elixir 1.3 as well, so this was a choice of upgrading to that with Elixir 1.3 or simplifying dependencies and using the base Elixir 1.3 libraries).

**Comment by akira** [comment]
Did a version bump to 0.7.3 with {:timex, "~> 2.0"} in #209

**Comment by smdern** [comment]
Could there be a new semver for Exq w/ elixir 1.3. This is a bummer for anyone wanting to use timex 3.0 and elixir 1.3. Ideally the Elixir 1.3 version of Exq can ditch Timex all together..

**Comment by akira** [comment]
@smdern Yes, I am planning to release a new semver for Exq with Elixir 1.3, which has Timex removed.  If you'd like to use it until then you can use master.

**Comment by goofansu** [comment]
@akira I've upgraded elixir to 1.3. Is the master branch production ready?

**Comment by akira** [comment]
@goofansu yes, the master branch is ready for use.

**Comment by goofansu** [comment]
@akira Thank you. I'm switching to master now.
