### ISSUE TITLE
Timex + Elixir 1.3

### ISSUE THREAD

**Issue by smdern** [akira/exq#210]
https://github.com/akira/exq/issues/201 makes sense for pre-elixir 1.3 versions, but anyone whose using Elixir 1.3 + Timex v3+ is screwed. Could we create two different semvers for pre/post elixir 1.3?

**Comment by akira** [comment]
FYI master version is on Elixir 1.3 with Timex removed.   I am going to release a new version for Elixir 1.3, guess it would be 1.0+.

**Comment by smdern** [comment]
> FYI master version is on Elixir 1.3 with Timex removed. I am going to release a new version for Elixir 1.3, guess it would be 1.0+.

:+1: I can use master for now. Thank you. I'll leave this open for now, for anyone else that has similar concerns.

**Comment by tlvenn** [comment]
Any update on this @akira ?

**Comment by akira** [comment]
@tlvenn I haven't see any issues reported on this, I can publish a hex release for this soon (this weekend).

**Comment by akira** [comment]
Just released new hex version for this.
