### ISSUE TITLE
Error: already started when running from release

### ISSUE THREAD

**Issue by pdilyard** [akira/exq#212]
Running my app with `iex -S mix` works fine, but when I build a release with `exrm`, I get the following error:

```
[info] Application exq exited: Exq.start(:normal, []) returned an error: already started: #PID<0.1594.0>
{"Kernel pid terminated",application_controller,"{application_start_failure,exq,{{already_started,<0.1594.0>},{'Elixir.Exq',start,[normal,[]]}}}"}
```

The release in question is built with the same config and environment as when I run `iex -S mix`.

Elixir version: `1.3.2`
exq version: `0.7.0`
exrm version: `1.0.8`

**Comment by pdilyard** [comment]
Found that this issue is fixed if I remove exq_ui from the build. It must be trying to start exq even though it's already started.

**Comment by akira** [comment]
Should be fixed by in exq_ui https://github.com/akira/exq_ui/pull/34
