### ISSUE TITLE
Issue regarding Timex library

### ISSUE THREAD

**Issue by HirenBhalani-BTC** [akira/exq#214]
I have configured Exq with Elixir 1.3.2 and Phoenix 1.2.0.

when I start phoenix server it's showing me errors.
I gon error in below lines.
> Time.now
> (UndefinedFunctionError) function Time.now/0 is undefined or private.

> Timex.time.now(:microsecond)
> ** (UndefinedFunctionError) function Timex.Time.now/1 is undefined or private

**Comment by akira** [comment]
@HirenBhalani-BTC are you using `master` or the version from hex?

**Comment by HirenBhalani-BTC** [comment]
I have used exq 0.7.2.

**Comment by akira** [comment]
@HirenBhalani-BTC can you try the latest on the master branch and report back.  Thanks!

**Comment by HirenBhalani-BTC** [comment]
Ok, sure.

**Comment by nburkley** [comment]
I was running into the same issue, using Elixir `1.3.3`, Phoenix `1.2.1` and Timex `3.0.8`. Everything's working fine using the latest exq version for `master`. Thanks!

**Comment by doomsplayer** [comment]
exq on hex is not working anymore. It is pretty hazardous to run a git version of package on production.

**Comment by akira** [comment]
@doomsplayer I just released a new version on hex.
