### ISSUE TITLE
Retry False

### ISSUE THREAD

**Issue by taylorbrooks** [akira/exq#215]
Any way to add config on a per worker basis for deciding whether or not to retry a job?

**Comment by akira** [comment]
I don't have much time to make this change, but if anyone wants to take a crack at a PR I would gladly work with them.

**Comment by jeroenvisser101** [comment]
@akira this can be closed now that #225 is merged?

**Comment by taylorbrooks** [comment]
Is the new version of the package cut and published on Hex?

**Comment by akira** [comment]
@taylorbrooks Just published 0.8.2 with this version
