### ISSUE TITLE
How to kill busy jobs?

### ISSUE THREAD

**Issue by pytong** [akira/exq#235]
I have a lot of busy jobs that are not going away. The button "clear worker list" seems to do nothing.
I also tried to kill the pid one by one, but the busy jobs are still there.

`Process.exit(pid(0,449,0), :kill)`
`flush`

**Comment by akira** [comment]
Is this the busy worker list on the UI - maybe is it related to issue #227 which is not fixed yet? Basically if you kill the system while worker is busy, the "busy" workers on the UI are not cleaned up. It is stale stats data, the workers may not actually be busy. 

Good catch on "clear worker list", it doesn't seem to refresh the list (it seems that reloading the page it is actually cleared?).  I added https://github.com/akira/exq_ui/issues/40.

**Comment by pytong** [comment]
You are right about the stale stats. I checked the status of the pid, they are not alive.

**Comment by akira** [comment]
OK, thanks for checking, should have a fix this weekend.

**Comment by akira** [comment]
@pytong fixed this, it is on master (not yet released).

**Comment by pytong** [comment]
Thank you.

**Comment by akira** [comment]
@pytong sure, let me know if works, can reopen if not
