### ISSUE TITLE
Can't start if sidekiq started

### ISSUE THREAD

**Issue by belousovAV** [akira/exq#244]
Sidekiq 4.2.9
Redis 3.2.8
Exq 0.8.4
Can't start if sidekiq started:

> 06:31:11.719 [error] GenServer Exq.Stats terminating
> ** (Poison.SyntaxError) Unexpected token at position 0: i
>     (poison) lib/poison/parser.ex:57: Poison.Parser.parse!/2
>     (poison) lib/poison.ex:83: Poison.decode!/2
>     (exq) lib/exq/serializers/json_serializer.ex:56: Exq.Serializers.JsonSerializer.decode_process/1
>     (exq) lib/exq/redis/job_stat.ex:63: anonymous fn/1 in Exq.Redis.JobStat.cleanup_processes/3
>     (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
>     (exq) lib/exq/redis/job_stat.ex:63: Exq.Redis.JobStat.cleanup_processes/3
>     (exq) lib/exq/stats/server.ex:106: Exq.Stats.Server.handle_call/3
>     (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
> Last message: {:cleanup_host_stats, nil, "ip-10-6-0-54"}
> State: %Exq.Stats.Server.State{queue: {[], []}, redis: Exq.Redis.Client}
> 06:31:11.721 [error] GenServer Exq terminating
> ** (stop) exited in: GenServer.call(Exq.Stats, {:cleanup_host_stats, nil, "ip-10-6-0-54"}, 5000)
>     ** (EXIT) an exception was raised:
>         ** (Poison.SyntaxError) Unexpected token at position 0: i
>             (poison) lib/poison/parser.ex:57: Poison.Parser.parse!/2
>             (poison) lib/poison.ex:83: Poison.decode!/2
>             (exq) lib/exq/serializers/json_serializer.ex:56: Exq.Serializers.JsonSerializer.decode_process/1
>             (exq) lib/exq/redis/job_stat.ex:63: anonymous fn/1 in Exq.Redis.JobStat.cleanup_processes/3
>             (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
>             (exq) lib/exq/redis/job_stat.ex:63: Exq.Redis.JobStat.cleanup_processes/3
>             (exq) lib/exq/stats/server.ex:106: Exq.Stats.Server.handle_call/3
>             (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
>     (elixir) lib/gen_server.ex:737: GenServer.call/3
>     (exq) lib/exq/stats/server.ex:66: Exq.Stats.Server.cleanup_host_stats/3
>     (exq) lib/exq/manager/server.ex:335: Exq.Manager.Server.rescue_timeout/2
>     (exq) lib/exq/manager/server.ex:206: Exq.Manager.Server.handle_cast/2
>     (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
>     (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
>     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
> Last message: {:"$gen_cast", :cleanup_host_stats}
> State: %Exq.Manager.Server.State{enqueuer: Exq.Enqueuer, middleware: Exq.Middleware.Server, namespace: nil, node_id: "ip-10-6-0-54", pid: #PID<0.1394$
> 06:31:11.723 [info] Application exq exited: shutdown

**Comment by akira** [comment]
I have a workaround in #245. Should work in master. 

I will be taking a look at updating the format support in the future.
