### ISSUE TITLE
how to run jobs repeatedly every X hours

### ISSUE THREAD

**Issue by egeersoz** [akira/exq#246]
I understand scheduling a job X minutes from now using `enqueue_in`.

I also understand scheduling a job to start at a specific time using `enqueue_at`.

But what I need to do is to run a job once every 24 hours. For example, run every morning at 6 AM and perform some task.

Can this be done with Exq?

**Comment by j-mcnally** [comment]
I dont think scheduled jobs are part of exq core.

**Comment by akira** [comment]
@egeersoz you can use Quantum for this - https://github.com/c-rack/quantum-elixir

**Comment by akira** [comment]
@egeersoz see #77 

I'm open to taking in an implementation of this, but don't have bandwidth to implement.

**Comment by egeersoz** [comment]
Thanks @akira . I was hoping to avoid using two different task scheduling libraries, but I guess I have no choice since I'm also pretty busy with an ongoing project. Maybe we can put the enhancement tag on this issue and keep it open for someone else to take a look at?

**Comment by akira** [comment]
Sure, it's tracked by #77 which has the tags.  Will keep that one open.

**Comment by lucasprag** [comment]
There is also https://github.com/activesphere/exq-scheduler if you haven't found it yet @egeersoz 👍
