### ISSUE TITLE
It's possible to quite queue like sidekiq?

### ISSUE THREAD

**Issue by allanbatista** [akira/exq#250]
Hi,
It's possible to quite queue like sidekiq?

**Comment by akira** [comment]
Hi, 
You can call "unsubscribe" on the queue, which means it will stop accepting new jobs, but will still keep working on existing ones. This is only applies to a single node  Is this what you are looking for?

https://github.com/akira/exq/blob/master/lib/exq.ex#L51

If not, let me know what your use case is and what this feature would be / how you would use it.

**Comment by allanbatista** [comment]
@akira thnks!

So, another question. Has some easy way to "unsubscribe" in many servers at same time and "re-subscribe" when necessary?

**Comment by akira** [comment]
@allanbatista at the moment there isn't a way to unsubscribe many servers at the same time.

**Comment by allanbatista** [comment]
@akira thnks. pls close this issue. :+1:
