### ISSUE TITLE
Is there a way to pattern match Ruby module name?

### ISSUE THREAD

**Issue by jackalcooper** [akira/exq#254]
If the corespondent module is not defined in Elixir, an exception is raised. Is there a way to pattern match Ruby module name rather than having to specifically define all the workers in Elixir?

**Comment by akira** [comment]
Yes, there's a way to do this. You can plug in a custom middleware after Job:

https://github.com/akira/exq/blob/master/config/config.exs#L21

Something like:
```
config :exq,
  middleware: [Exq.Middleware.Stats, Exq.Middleware.Job, MyCustomMiddleware, Exq.Middleware.Manager,
    Exq.Middleware.Logger]
```

For example, here is how it usually gets assigned:
https://github.com/akira/exq/blob/master/lib/exq/middleware/job.ex#L11

Your module can change the  `worker_module` to be a specific worker:

```
defmodule MyCustomMiddleware do
  @behaviour Exq.Middleware.Behaviour

  def before_work(pipeline) do
    # in case you need job data
    job = pipeline.assigns.job
   
    # reassign to one module (can be more selective)
    mod = "CatchAllWorker"
    module = String.to_atom("Elixir.#{mod}")

    pipeline
    |> assign(:worker_module, module)
  end

  def after_processed_work(pipeline) do
    pipeline
  end

  def after_failed_work(pipeline) do
    pipeline
  end
end
```

This should work, but I haven't tested this so it could have typos.  If this is a common need by others, it could be abstracted out by a module similar to `Serializer` or `NodeIdentifier` that can be configured more easily.
