### ISSUE TITLE
Could starting exq app be optional?

### ISSUE THREAD

**Issue by jackalcooper** [akira/exq#255]
I'm using exq in an umbrella project, currently I don't want to start exq app every time because the sub-app depends on exq is still under development.

**Comment by jackalcooper** [comment]
Could it be like Ecto's Repo? If it fails to connect to DB, it doesn't crash the Erlang VM.

**Comment by j-mcnally** [comment]
Yeah or I believe you could run it as a standalone... don't quote me on
that though it's probably changed.

**Comment by akira** [comment]
@jackalcooper Agreed that this would be a good feature. I would be open to a PR for this, or I could take a look at doing this, but not sure of timing on that.

**Comment by akira** [comment]
@jackalcooper This looks fairly simple, should be able to get to this next couple of days.

**Comment by jackalcooper** [comment]
@akira That would be great!

**Comment by akira** [comment]
@jackalcooper I added the option, it is on master branch

**Comment by jackalcooper** [comment]
@akira Thanks Alex! I added a line of doc for it https://github.com/akira/exq/pull/258
