### ISSUE TITLE
Requeue failed jobs when a node crashes and does not come back online.

### ISSUE THREAD

**Issue by lpil** [akira/exq#261]
Currently requeuing of jobs after a crash is the responsibility of a new node with the same node ID as the crashed node. The system would be more resilient to failure (and it would be easier to resize the cluster) if there was a mechanism for other nodes to perform this clean up.

## A possible approach

I've little experience in this kind of systems, but I was thinking something along these lines could work:

1. Nodes heartbeat to Redis periodically. This is recorded using their node id and a timestamp using Redis local time.
    - A set sorted by timestamp could be employed here to allow more efficient time based querying.
    - Heartbeats could be piggybacked onto the existing polling for jobs to prevent additional network overhead. Lua scripting may be required here.
2.  Nodes periodically check to see if any members of the set have not registered a heartbeat within a configurable set timeout. If a node is found to be missing they can requeue their jobs and deregister the node from the records in Redis.

There are problems with this approach:

If a node is isolated from Redis and no longer able to heartbeat (say, during a network partition) a node may be falsely assumed to be dead, causing the jobs in progress when the partition started to be requeued even though they finished successfully. Depending on your workload this may not be acceptable.

- Idempotent jobs can prevent this from causing damage, but would still cost worker time.
- Using a longer heartbeat timeout before requeuing can reduce the chance of this happening.

### Implementation

If we implement the heartbeat (step 1) in Exq the second part can be implemented as an additional library that depends on Exq. This gives users a way to opt into this behaviour, and helps Exq avoid having to manage deprecating this feature if it is decided that it is not wanted moving forward.

I don't believe that this library would need to share any configuration or code with Exq other than the address of the Redis instance being used and the Redis namespace.

It would be beneficial for the protocol that Exq uses to be documented and declared stable enough for this library to also use (as it will be modifying the same keys that Exq modifies).

---

Would be great to hear your thoughts. Even if this proposed approach isn't right I think this issue is one that would be good to try and solve.

Cheers,
Louis

**Comment by akira** [comment]
+@joshk, we spoke about this. 

1. Having a node level heartbeat would work well for this. I think this is what would be needed to allow other nodes to take over when a node disappears. 

2. As you mentioned, nodes can check periodically if any heartbeats are stale in sorted set, and requeue job if so.

Job should be idempotent, so I don't think we should attempt to resolve the issue with disconnected nodes. The heartbeat timeout can be configurable.  

As far as implementation being part of this or a separate lib, I can see it being either way. If the current implementation stays the same with regards to backup queue keys, etc, it can be a separate lib. However, if that part changes or is not compatible with current implementation, it could have to be part of the library. 

As far as queueing, the protocol for Exq is stable as it follow the Sidekiq protocol. I think some differences that need to be fixes are in the stats section (for keeping track of busy processes, what work is currently being done, etc).
