### ISSUE TITLE
Requeue job without throwing an error

### ISSUE THREAD

**Issue by lpil** [akira/exq#262]
Hello!

Is there an API for a job requeueing itself without throwing an exception? I would like this so that for monitoring purposes I can differentiate between jobs that need to be retried later (say because an external service is down) and those that have failed due to an in-application error.

As an OTP fan I would expect the worker to be a behaviour that returns a different value depending on what needs to be done.

```elixir
:ok                          # Job successful
{:requeue, new_state}        # Requeue job
{:requeue, new_state, delay} # Requeue scheduling for a specific time
```

Clearly this isn't the case though. How might I do this?

**Comment by akira** [comment]
Can you use the regular enqueue API?

For example
```
def perform do 
   # Work here
   Exq.enqueue(Exq, "default", SameWorker, [])
   #or
   Exq.enqueue_in(Exq, "default", 3000, SameWorker, [])
end
```

**Comment by lpil** [comment]
That's great, thank you. :)

It it possible to preserve the retry count? If it has failed previously?

**Comment by akira** [comment]
There's no easy way to do that at the moment. I can see having an API similar to `worker_job` that will re-enqueue and take retry options. 

https://github.com/akira/exq/blob/master/lib/exq.ex#L72
