### ISSUE TITLE
Graceful shutdown draining workers

### ISSUE THREAD

**Issue by lpil** [akira/exq#263]
Hello!

When the VM shuts down normally it would be nice to allow the workers a period of time to finish, but not to wait longer than needed.

### Methodology

Add a new `WorkerDrain` child to the supervision tree, one that comes after the `Worker.Supervisior` and the `Manager.Server`. This process traps exits, but otherwise does nothing.

When the application starts to shut down the `WorkerDrain` process receives the shutdown message and starts a timeout erlang timer (with a configurable value). It then sends a messages to the `Manager.Server` prompting it to unsubscribe from all queues, and a queries `Worker.Supervisior` to obtain a list of the worker children.

It monitors each of the children and then enters a receive loop, waiting for the worker's exit signals. Once either all the workers have terminated or the timer timeout is up the `WorkerDrain` process exits, allowing the shutdown process to continue for the rest of the application.

### Prior art

- https://gist.github.com/aaronjensen/33cc2aeb74746cac3bcb40dcefdd9c09
- https://github.com/phoenixframework/phoenix/pull/1925/files

How does that sound? I'm happy to work on this feature. Also happy to implement it in another library, though I'd like to add an `Exq.unsubscribe_all(pid)` function to Exq. :)

Thanks,
Louis

**Comment by akira** [comment]
Thanks for the analysis and the prior art links!  I would definitely be in favor of all this. I think this should be put in Exq, and not as a separate library. I would definitely appreciate if you would like to take a crack at this.

FYI, there is already a worker_shutdown timeout configuration property, so this should properly execute this. Also, I was just digging into the code, and found a typo with the way the workers are currently setup which needs to be fixed (workers still get shutdown with this but this is obviously wrong):  https://github.com/akira/exq/blob/master/lib/exq/worker/server.ex#L32 which should be `start_link` instead.

**Comment by akira** [comment]
Fixed above issue with start_link in #265.  There are already some tests for graceful shutdown feature, see the tests made @pending as part of that PR. 

Tests are:
https://github.com/akira/exq/blob/master/test/exq_test.exs#L313 and https://github.com/akira/exq/blob/master/test/exq_test.exs#L326

**Comment by lpil** [comment]
Great, thanks. :)
