### ISSUE TITLE
Start phoenix console iex will double exq workers

### ISSUE THREAD

**Issue by thanhn08** [akira/exq#272]
Hello, I am using `exq` with `Phoenix` and start `exq` by using supervision tree.... It ran well with my phoenix server but the problem arises when i start console using `MIX_ENV=prod iex -S mix`... it seems to me that starting the console will also start `exq` which double the `concurrency workers` which then pick the jobs in redis to run.... this behavior is not what i want, as when i close the console, the jobs might be stuck or work incorrectly

is there any suggestion on this? not sure i am in the right direction but I think i want to either
1. start exq with phoenix server and not console
2. start exq as a standalone app but still loads the config / code / context of my project (be able to access ecto, etc)

**Comment by akira** [comment]
Can you run with ` iex -S mix run --no-start`

**Comment by akira** [comment]
Posting for future reference - this was answered on elixir-lang slack. 

"`IEx.started?` is `true` if run from iex, e.g. `iex -S mix`, `false` otherwise e.g. `mix phx.server` — you could build a different supervisor spec reactively"
