### ISSUE TITLE
Throttling/debouncing of jobs

### ISSUE THREAD

**Issue by jfrolich** [akira/exq#275]
Hi,

I would like to create a middleware for debouncing particular jobs. To make it a little easier to understand the functionality I am looking for I'll describe it with a concrete example.

The idea is to debounce message notifications for chat with the first one instantly sent. So people get an email notification when there is a new message. When there is a new message I would like to notify people. If there are more messages afterwards I would like to only send a notification if there has been not been a message the past few minutes.

Perhaps it could be implemented with a middleware that checks if for particular params of `notification` there is a `bundled_notification` already available, otherwise send it, and create an inactive flagged `bundled_notification` that runs in 3 minutes time. If another message comes in (within 3 minutes) the `bundled_notification` is deleted and a another one is scheduled for 3 minutes and flagged active (with added metadata). If a `bundled_notification` is run that is not active nothing is being done. If an active `bundled_notification` is being run the appropriate task is being run (perhaps `perform_multi` or so).

Does anyone more familiar with the codebase have some idea's how to implement this using Middleware?

**Comment by ananthakumaran** [comment]
We have recently added some options that might help with throttling https://github.com/akira/exq/pull/421. But given that the request is at per user level, I am not sure anything else can be done at exq other than building this yourself. I am closing this as it's not an actionable item.
