### ISSUE TITLE
Resubscribe to queue after Exq crash for dynamic queue subcriptions

### ISSUE THREAD

**Issue by ch33foong** [akira/exq#278]
Hi there,

Correct me if I am wrong, when subscribed dynamically to a queue and if Exq crashed and restarted it does not resubscribe to the queue again.

Is there a way to have Exq resubscribe to the previous subscribed queue? e.g is there any hook to detect Exq is started and resubscribe to the queue?

**Comment by akira** [comment]
Hello, 
That is correct, the queues would be reset. I think the best course would be to save the queue configuration list in a separate process/ets table and retrieve this on Exq startup. I'm not sure when I can get to this, I can definitely review a PR for it if anyone has a chance.

**Comment by ch33foong** [comment]
Hey,

My use case was to subscribe to queue based on the queue name passed in via environment variable. What I did was reading the env variable in my app module and dynamically subscribe to the queue by calling 

`Exq.subscribe()`

After spending some time reading part of the Exq code (I am still new to Elixir), I realise that I can pass in the queue name like this 

`supervisor(Exq, [queues: [System.get_env("QUEUE")]])` 

Doing this the queue were not reset after Exq exited, guess this is the same as if the queue is configured via config

So it's all good now :)
