### ISSUE TITLE
Most common way to run in production

### ISSUE THREAD

**Issue by atomkirk** [akira/exq#283]
What is the most common (best?) way to run exq in production?

In Ruby and most other languages, you need a pool of worker instances to run your jobs (separate from web instances). Does that still make sense with elixir/erlang or do most projects just run the workers in erlang processes in the web instances?

If the answer is separate worker instances, is it possible to have the same web application installed on the worker instances  (like ruby) and just run exq and ecto?

**Comment by akira** [comment]
I think this is up to your situation. If it is a small application with low volume of messages, you can potentially run the workers as well on the same instance as Phoenix.  However, if you have a large volume of web traffic, and processing large amounts of message, you may want to split out the workers from the web application. 

There aren't hard and fast rules, as it depends on your use case and scale. You can start with an integrated setup, and then split them out as needed.

**Comment by atomkirk** [comment]
so I'm thinking i could decide which supervision tree to run in an erlang release based on an environment variable that would be different per web/worker instances. Does that seem reasonable?
