### ISSUE TITLE
module (worker) not found ... I must be missing something :)

### ISSUE THREAD

**Issue by justmark** [akira/exq#286]
I'm running exq in standalone mode on Elixir 1.5.1

I currently have a Sidekiq implementation.  We're migrating services over to Elixir and have chosen Exq to handle the migration.  I have some test jobs that our Ruby app is pushing into Sidekiq, and I can see these being pulled up by Exq, but the module to handle them can't be found even though it is defined in the lib directory.

```
09:35:34.872 [info]  Elixir.TestWorker[9ac4e0328e0bb4b4216b5592] start

09:35:34.900 [error] Process #PID<0.171.0> raised an exception
** (UndefinedFunctionError) function TestWorker.perform/3 is undefined (module TestWorker is not available)
    TestWorker.perform("val1", 83, "val2")
    lib/exq/worker/server.ex:141: anonymous fn/4 in Exq.Worker.Server.dispatch_work/3
```

I do have a TestWorker defined in lib:

```
defmodule TestWorker do

  def perform(val1, val2, val3) do
  	job = Exq.worker_job()
  	IO.inspect job
  end

end
```

Is there some configuration necessary to get Exq to recognize this module?  

Thanks

**Comment by justmark** [comment]
Figured it out.  Was running with mix exq.run and should've been doing mix run --no-halt

**Comment by spectator** [comment]
Running into exactly the same issue :( 

@justmark do you happen to remember if that was `mix run --no-halt` (which doesn't work for me) or it was something else? thanks!

**Comment by akira** [comment]
@spectator you have to make sure the namespace setting is also correct, which can be configured in config.ex

**Comment by justmark** [comment]
@spectator Yes, `mix run --no-halt` worked perfectly.

**Comment by spectator** [comment]
@akira @justmark thank you both for responding!

@akira sorry, I should have been more clear, getting exactly the same error, the only difference is module name. Works fine if I just call it directly in `iex -S mix`.

I'm not running it alongside Sidekick but jobs are scheduled w/o starting workers from readme `Exq.Enqueuer.enqueue(Exq.Enqueuer, "default", MyWorker, [])` and then I just call `mix exq.run` which keeps throwing this error, retry, and that again. Run out of ideas what could be wrong 🤔

**Comment by spectator** [comment]
@akira would you be so kind to have a quick look at this bare phoenix app that demonstrates this issue https://github.com/spectator/mix_exq ?

```
mix mix_exq.scheduler
mix exq.run
```

the output will have this

```
00:38:48.472 [info]  Elixir.MixExq.Workers.MyWorker[f9947562-680c-49f3-8ea8-51afd3a987fb] start

00:38:48.506 [error] Process #PID<0.164.0> raised an exception
** (UndefinedFunctionError) function MixExq.Workers.MyWorker.perform/1 is undefined (module MixExq.Workers.MyWorker is not available)
    MixExq.Workers.MyWorker.perform(1)
    lib/exq/worker/server.ex:141: anonymous fn/4 in Exq.Worker.Server.dispatch_work/3
```

**Comment by spectator** [comment]
In case somebody runs into this, for now I solved it with custom mix task that does exactly the same thing Exq mix task does https://github.com/spectator/mix_exq/commit/51d8221ee2555cb7e389a77bdd63bb2e13b8526a

**Comment by eprothro** [comment]
I have the same issue. Using the `mix exq.run` standalone task results in my app code not being loaded.

Copying the task into my app works around this, as @spectator did:

```
defmodule Mix.Tasks.Worker.Run do
  use Mix.Task

  @shortdoc "Starts Exq in standalone mode"

  def run(_args) do
    {:ok, _} = Exq.start_link
    IO.puts "Started Exq"
    :timer.sleep(:infinity)
  end
end
```

```
mix worker.run
```

@justmark If im thinking correctly, running `mix run --no-hault` is not the same thing as running `mix exq.run`, the former is running everything, not just exq in standalone mode

@akira I don't think this issue is about Sidekiq not finding a job, but rather that the standalone mix execution not loading the app code so tasks can't actually be dispatched.

**Comment by antonioparisi** [comment]
I'm still experiencing this issue. I tried with both `start_on_application` set to `true/false` but still encountering the same issue.

Scenario:
I deploy the code, run the shell remotely with `iex -S mix` then:
`Enum.each(0..50, &(Exq.enqueue(Exq, "default", X.Jobs.I.FooBarJob, [&1]) end))`

I get:
```
Process #PID<0.2240.15> raised an exception ** (UndefinedFunctionError) function X.Jobs.I.FooBarJob.perform/1 is undefined (module X.Jobs.I.FooBarJob is not available) X.Jobs.I.FooBarJob.perform(18617) (exq) lib/exq/worker/server.ex:186: anonymous fn/4 in Exq.Worker.Server.dispatch_work/3
````

what am I doing wrong?

at the moment this is my configuration:
```
config :exq,
  host: System.get_env("REDIS_HOST"),
  port: System.get_env("REDIS_PORT"),
  password: System.get_env("REDIS_PASSWORD"),
  namespace: "exq",
  concurrency: System.get_env("REDIS_CONCURRENCY") |> String.to_integer,
  queues: ["default"],
  poll_timeout: 50,
  scheduler_poll_timeout: 200,
  scheduler_enable: true,
  max_retries: 3,
  shutdown_timeout: 5000,
  start_on_application: false,
  redis_options: [
    ssl: true
  ],
  middleware: [
    Exq.Middleware.Stats,
    Exq.Middleware.Job,
    Exq.Middleware.Manager,
    Exq.Middleware.Logger
  ]

config :exq_ui,
  web_namespace: "jobs",
  server: true


lib/X/application.ex:
...
children = [... supervisor(Exq, []), ...]
...
```

Regards,
Antonio

**Comment by antonioparisi** [comment]
@justmark @akira @spectator @eprothro any hint to give me?

**Comment by danicuki** [comment]
👍

**Comment by danicuki** [comment]
same issue here

**Comment by ananthakumaran** [comment]
Either use `mix do app.start, exq.run` or `mix run --no-halt`. README has been updated with the correct instruction.
