### ISSUE TITLE
Add support for redis sentinel

### ISSUE THREAD

**Issue by ananthakumaran** [akira/exq#292]
We have been using the [fork](https://github.com/akira/exq/compare/master...ananthakumaran:sentinel) at production for sometime. If there is interest, I can prepare a PR, though we need to figure out which approach needs to be taken. [redix_sentinel](https://github.com/ananthakumaran/redix_sentinel) is api compatible with redix except for the start_link method. so we could make the module_name & start_link args configurable. At this point, I am not sure whether sentinel support would be added in redix, see https://github.com/whatyouhide/redix/issues/51. I am open to other ideas also.

**Comment by akira** [comment]
Not ideal solution of using a fork of Redix. Are you planning on keeping redix_sentinel up to date with redix / do you think it will get merged into master for Redix?  Are there other maintained Redis elixir libs that have sentinel support?

**Comment by ananthakumaran** [comment]
> Are you planning on keeping redix_sentinel up to date with redix ? 

Yes, we are using it in production and I intend to keep it upto date

> Do you think it will get merged into master for Redix?

At this point I don't think so. from his response to whatyouhide/redix#51 and the fact that he maintains a seperate repo for pubsub, I figure he wants to keep the core small.

> Are there other maintained Redis elixir libs that have sentinel support?
Not that I know of

**Comment by ondrejbartas** [comment]
What about enabling user to pass custom instance of Redis? Then you don't need to take care about redis options at all (same as sidekiq does) and also by this you will be able to pass Redix sentinel instead of Redix

**Comment by akira** [comment]
@ondrejbartas good suggestion, @ananthakumaran can we have something you can set via configuration on which Redis module you can use for overriding this? Then you can pass in the sentinel module and have that dependency in your application. However, we can use the default Redix for people that do not want to use sentinel.

**Comment by ananthakumaran** [comment]
sure, I was proposing the same thing (make module/start_link args configurable). I will try to put together a PR and we can discuss the details there.
