### ISSUE TITLE
Jobs depending on other jobs

### ISSUE THREAD

**Issue by johnnyji** [akira/exq#295]
Hi there!

I was wondering how one would approach dealing with jobs dependant on the success of previous jobs in Exq? Here's an example:

We want to sync both an **Invoice** and a **Payment** to Quickbooks Online using Exq. The catch here is that the payment MUST be synced after the invoice has been successfully synced, otherwise there's a dependency error.

I have tried to `case` match on the response from `Exq.enqueue` used to sync the invoice, and only in the `{:ok, uid}` match scenario, proceed with my payment syncs `Exq.queue` calls. However, this doesn't seem to do any type of delaying.

My biggest issue right now is that the jobs are happening so fast they're not waiting for the Quickbooks response before proceeding to the next job. Is there some sort of way to delay the execution of the next job in the chain until specified to do so?

I looked through the docs and issues and didn't seem to find much of an answer regarding this. Any guidance/help would be appreciated!!

Thanks for the dope library

**Comment by bschaeffer** [comment]
There's [`Exq.enqueue_in`](https://hexdocs.pm/exq/Exq.html#enqueue_in/5) and [`Exq.enqueue_at`](https://hexdocs.pm/exq/Exq.html#enqueue_at/5), but I really don' think you need those methods as this seems more like an application problem and really not related to exq.

You should probably head over to https://elixirforum.com/ and discuss your problem over there.

**Comment by johnnyji** [comment]
@bschaeffer gave some awesome insight on slack!

It was really just the way I approached it, he suggested a simple answer that just works. Creating a completely separate worker that synced both the invoices and their dependant payments together.
