### ISSUE TITLE
Reduce unnecessary read ets times on connection.q/2 qp/2 qp!/2

### ISSUE THREAD

**Issue by zhongwencool** [akira/exq#304]
https://github.com/akira/exq/blob/9673cb5bb739f235aac72eee604779122152073d/lib/exq/redis/connection.ex#L159
----
```elixir
def q(redis, command) do
    redis_worker_module().command(redis, command, [timeout: Config.get(:redis_timeout)])
  end

  def qp(redis, command) do
    redis_worker_module().pipeline(redis, command, [timeout: Config.get(:redis_timeout)])
  end

  def qp!(redis, command) do
    redis_worker_module().pipeline!(redis, command, [timeout: Config.get(:redis_timeout)])
  end
```
The frequency of calling `q/2,qp/2,qp!/2` is very high.
`application:get_env/2` read config from ets table, the speed of reading ets table grows more and more slowly as concurrent volumes grows. the detail benchmark see: https://github.com/zhongwencool/erl-env#benchmark, especially when CPU resources are exhausted.
How about change to 
```elixir
def q(redis, command,  redis_worker \\ redis_worker_module(), options \\ [timeout: Config.get(:redis_timeout)]) do
    redis_worker.command(redis, command, options)
  end

  def qp(redis, command, redis_worker \\ redis_worker_module(), options \\ [timeout: Config.get(:redis_timeout)]) do
    redis_worke.pipeline(redis, command, options])
  end

  def qp!(redis, command, redis_worker \\ redis_worker_module(), options \\ [timeout: Config.get(:redis_timeout)]) do
    redis_worker.pipeline!(redis, command, options)
  end
```
If still worry about https://github.com/akira/exq/pull/296, a more moderate solution which include `eenv` applicaiton to replace `applicaiton:get_env/2-3`, the benchmark show `eenv:get/2-3` is 7x faster then `application:get_env/2-3`, cost less CPU resources. :)

**Comment by ananthakumaran** [comment]
When you compare difference between normal call vs application.get_env + mfa call, obvisously the second one is going to be slow compared to first one. But we have to factor in the next call also, which touches the network. In real life it's very likely that the whole delay is going to depend on the network call(I have already provided a benchmark in my last PR to show that is the case). I have also explained the disadvantage of moving the resolution to compile time. Again redis server is single threaded, making requests from 100s of client is not going to increase the throughput.

**Comment by zhongwencool** [comment]
1. It's the bottlenecks never gonna happen?
All application store config in one ets, not only lookup by `exq`,  in theory, it is possible to encounter bottlenecks(very small probability).
2. Can `exq` get enough benefits by `eenv` ?
Just my own opinion, add `eenv` will decrease the above risks(make `exq` robust). faster and stable without the disadvantage of moving the resolution to compile time.
we should analysis of the risk(weakness) of **add eenv** to determine whether to modify or not.
If do not feel worth it, we can optimize after actually reach a bottleneck.

**Comment by ananthakumaran** [comment]
This issue is not valid anymore. We have removed the call to `redis_worker_module()`
