### ISSUE TITLE
No support for unix socket?

### ISSUE THREAD

**Issue by jarmo** [akira/exq#308]
My redis instance does not listen on TCP. Instead it is only serving over unix socket. I can't seem find that Exq supports unix sockets instead of TCP. I've tried different ways of configuring Exq to connect over unix socket but I've always greeted with a connection error message.

Does Exq support unix sockets or not?

**Comment by akira** [comment]
We are using [Redix](https://github.com/whatyouhide/redix) for Redis connection library - I'm not sure if it supports this. Looking at it briefly, I have the feeling it does not. Maybe can you ask in Redix issues section? If supported, a PR for adding socket support would be useful and accepted.

**Comment by jarmo** [comment]
I've opened an issue regarding this at redix. I will keep you updated if there's any development.

**Comment by jarmo** [comment]
I did get a reply at https://github.com/whatyouhide/redix/issues/91 but since I'm pretty new to Elixir then most of it didn't make any sense to me for me to create any PR-s in the near future. Maybe someone else can decipher that reply and add unix sockets support to Exq as well.

**Comment by ananthakumaran** [comment]
Exq now supports [`redis_options`](https://github.com/akira/exq#sentinel) which is directly passed to Redix. Unix sockets can be used by setting the relevant options.
