### ISSUE TITLE
Can't make enqueue_at to work.

### ISSUE THREAD

**Issue by janna-delacruz** [akira/exq#314]
Hi, newbie here.

I'm trying to schedule a job by providing the specific date and time, but I can't seem to make it work. It returns this error.

> [error] GenServer Exq.Enqueuer terminating
** (FunctionClauseError) no function clause matching in DateTime.to_unix/2
    (elixir) lib/calendar/datetime.ex:216: DateTime.to_unix(#Ecto.DateTime<2018-04-26 00:00:00>, :microseconds)
    (exq) lib/exq/support/time.ex:18: Exq.Support.Time.unix_seconds/1
    (exq) lib/exq/support/time.ex:13: Exq.Support.Time.time_to_score/1
    (exq) lib/exq/redis/job_queue.ex:66: Exq.Redis.JobQueue.enqueue_job_at/6
    (exq) lib/exq/enqueuer/server.ex:45: Exq.Enqueuer.Server.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:enqueue_at, {#PID<0.1047.0>, #Reference<0.448548668.3095658497.107107>}, "member_activation", #Ecto.DateTime<2018-04-26 00:00:00>, Innerpeace.Job.Worker.ActivateMember, ["arg2"], []}}
State: %Exq.Enqueuer.Server.State{namespace: "exq", redis: Exq.Redis.Client}

Here's my code.

`Exq.enqueue_at(Exq, "member_activation", Ecto.DateTime.cast!("2018-04-26 00:00:00"), Job.Worker.Activate, ["arg2"])`

I've been stuck here for two days. Please enligthen me. Thank you.

**Comment by ananthakumaran** [comment]
The time value passed should be compatible with `Calendar.datetime` type. Either use the DateTime in the standard library or use some library(example Timex) that is compatible with `Calendar.datetime`

**Comment by janna-delacruz** [comment]
Thanks for the tip! It's now working.
