### ISSUE TITLE
Enqueuer and worker deployed on a different server

### ISSUE THREAD

**Issue by janna-delacruz** [akira/exq#319]
Is it possible to have a separate app and deploy it in different servers for the enqueuer and worker?

What we what to do is to have a website queuing the jobs and another app to process it. The idea is that they will run on a separate server.

Thank you!

**Comment by ananthakumaran** [comment]
Yes, you can have multiple independent enqueuers (producers) and workers. You can even enqueue jobs from rails via sidekiq.

**Comment by janna-delacruz** [comment]
Could you give me an idea on how to do it?

**Comment by ananthakumaran** [comment]
check this https://github.com/akira/exq/pull/168 for details. Basically you have to set `start_on_application` to false and  add Exq to your supervision tree, you should pass mode as enqueuer like `Exq.start_link(mode: :enqueuer)`

**Comment by janna-delacruz** [comment]
@ananthakumaran thanks for the details. I've been trying to run `Exq.start_link(mode: :api)` but it always returns `{:error, {:already_started, #PID<0.526.0>}}`.

**Comment by janna-delacruz** [comment]
I'll start a new thread for my other question. Closing this now since my original question was answered already. Thank you for the help.
