### ISSUE TITLE
api mode not working?

### ISSUE THREAD

**Issue by janna-delacruz** [akira/exq#320]
I'm creating a system wherein the enqueuer and the worker is on a separate system/server. I got the enqueuer to work, but I can't seem to make the worker to run. Please correct me if I'm wrong, but as I understand it, I only need to run `Exq.start_link(mode: :api)` to start the workers. However, nothing is happening. Is there a function I need to call to run the workers? Please help me.

**Comment by ananthakumaran** [comment]
for worker you don't have to do anything special, just configure and let the application run.

**Comment by janna-delacruz** [comment]
It will automatically process the queue? The `start_on_application: false` is only for the enqueuer? Did I understand it correctly?

**Comment by janna-delacruz** [comment]
It's not working. Here is my worker config.

```
config :exq,
  host: "127.0.0.1",
  port: 6379,
  namespace: "exq",
  queues: [
    {"default", 50},
  ],
  scheduler_enable: true,
  max_retries: 0
```

```def application do
    [
      mod: {Worker.Application, []},
      extra_applications: [
        :logger,
        :runtime_tools,
        :db,
        :bamboo,
        :exq
      ]
    ]
  end
```

**Comment by janna-delacruz** [comment]
It's seems that the one app who enqueue the job is also the app that will process it. I changed the config of my enqueuer app to its original setup (details below). And all of the job in the queue starts.

**Comment by akira** [comment]
Here is documentation for the mode:
```
  * `default` - starts the default processes
  * `enqueuer` - starts processes which are responsible for job enqueueing
  * `api` - starts processes which are responsible for API usage
```

If you only want to enqueue, use `mode: :enqueuer`. For starting everything, that is the default mode and nothing needs be done. For only starting the API, you can use `mode: :api` - this is only for getting stats.  

The messages are enqueued to Redis, so it is not deterministic on which workers will get the messages - it will be distributed to all active workers in the system regardless of which server enqueues it.

**Comment by janna-delacruz** [comment]
Ok, thanks so much @akira. I'll try it again.

**Comment by janna-delacruz** [comment]
Got it to work. Thanks so much. :smile:
