### ISSUE TITLE
Exq dead jobs filling up Heroku Redis?

### ISSUE THREAD

**Issue by johnnyji** [akira/exq#322]
Hi there!

I've been having a weird error with my Heroku Redis. It seems that 99% of my Redis memory is being used by `exq:dead`, which I assume are dead jobs. Is there a way to always clear dead jobs programmatically? I never do retries in my Exq anyways and I'd like to just get rid of dead jobs if possible.

Could anyone advise?

(Dope library btw, many thanks!)

**Comment by ananthakumaran** [comment]
@johnnyji check https://github.com/akira/exq#dead-jobs, it's added in the last release, setting max_jobs to 0 will effectively keep it empty

**Comment by johnnyji** [comment]
@ananthakumaran Thanks! Just a side question, would there be any reason I would want to keep dead jobs around?

Also, is there a way to specify max_dead_jobs on a per queue basis?

**Comment by ananthakumaran** [comment]
> would there be any reason I would want to keep dead jobs around?
it could be re-enqueue them via sidekiq UI and might be useful in some cases

Also, is there a way to specify max_dead_jobs on a per queue basis?
no not possible now as everything goes to the same sorted set.
