### ISSUE TITLE
same pool of jobs?

### ISSUE THREAD

**Issue by spunkedy** [akira/exq#324]
I use `exq` in a kubernetes environment, where I need to have nodes come up and down.

I noticed this in the readme:

```
* You can use multiple Erlang nodes to process from the same pool of jobs.
```

Do I just need to have them all report the same node name with a custom node name implementation to have them all use the same pool?

**Comment by ananthakumaran** [comment]
Each worker should have different node identifer, but they should not
change on restart. The node identifier is used to find jobs that were not
finished when the worker crashed or did not shutdown cleanly. Stateful set
in kubernetes fits this constrain perfectly. By default hostname is used as
identifier, so you don't have to configure identifier with stateful set.

**Comment by spunkedy** [comment]
Thanks for the response. 

So let me make sure I understand.

If I put jobs into the queue, they will get processed by any node configured? Not just the one that pushed it onto the queue?

Does node identifier only come into play when a job is in the middle or crashed?


in re: StatefulSets, we use deployments because of rollback capability. 

This is my fear:

```
Node A schedules Job A for 4 hours from now
Node B comes online
Node A goes down
Job A doesn't get run because Node A enqueued
```

**Comment by ananthakumaran** [comment]
> If I put jobs into the queue, they will get processed by any node configured? Not just the one that pushed it onto the queue?

any worker can pickup a job from queue, doesn't matter who pushed it. Also retry could happen on any worker.

> Does node identifier only come into play when a job is in the middle or crashed?

mostly yes, if worker with identifier A crashed while processing job 1, then only worker with the same identifier can resurrect it back to the queue. Once resurrected, that job can again picked up by any worker. 

The reason for this constrain is, once Worker A start to work  on a job, it's difficult to detect from other nodes whether it's actually working or crashed.

**Comment by spunkedy** [comment]
Thanks for the clarification! That makes me feel a lot better from having to be forced into a named worker state.
