### ISSUE TITLE
Can't start phoenix applications

### ISSUE THREAD

**Issue by wethanet** [akira/exq#343]
receiving the following error when attempting to start the phoenix server.  

`** (Mix) Could not start application exq: Exq.start(:normal, []) returned an error: shutdown: failed to start child: Redix
    ** (EXIT) an exception was raised:
        ** (ArgumentError) unknown option: :backoff
            (redix) lib/redix/utils.ex:40: anonymous fn/1 in Redix.Utils.sanitize_starting_opts/1
            (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
            (redix) lib/redix/utils.ex:29: Redix.Utils.sanitize_starting_opts/1
            (redix) lib/redix/connection.ex:26: Redix.Connection.start_link/1
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3`

Seems like redix is now checking to see if the options are in an approved list, and exq is sending a :backoff options which is not accepted by redix.  FYI

My versions are
exq 0.12.1
redix 0.8.1

**Comment by ananthakumaran** [comment]
Closing this. backoff and other related options were removed by https://github.com/akira/exq/commit/2f33c951bd6b793e62beecbba7c024d870b14472
