### ISSUE TITLE
Enqueue jobs to be processed by Rails (or any other consumer)

### ISSUE THREAD

**Issue by joaodiogocosta** [akira/exq#352]
I'm in the process of migrating from Sidekiq to Exq and need to enqueue back to Redis a few jobs to be processed by Rails. There's documentation about processing jobs enqueued by Rails, but not the other way around.

So far I've tried:

```elixir
Exq.enqueue(Exq, "resource_saver", "ResourceSaverJob", ["arg1"])
```

But I'm getting the following error:

```elixir
(...)

18:10:07.780 [error] Process #PID<0.263.0> raised an exception
** (UndefinedFunctionError) function ResourceSaverJob.perform/0 is undefined (module ResourceSaverJob is not available)
    ResourceSaverJob.perform()
    (exq) lib/exq/worker/server.ex:141: anonymous fn/4 in Exq.Worker.Server.dispatch_work/3

(...)
```

So I'm assuming that Exq is expecting a worker module with the same name to exist in Elixir land, but the actual worker that will consume these jobs only exists on the Rails (Sidekiq) side.

Is there a way to enqueue jobs to be processed by other consumers out of the scope of the Elixir application (ex: Rails)?

**Comment by ananthakumaran** [comment]
I guess the job is being picked up by the elixir worker. You could try to add `mode: :enqueuer` in the config, which will prevent the worker from getting started

**Comment by joaodiogocosta** [comment]
I'm hoping that Exq will ignore Jobs from queues it doesn't know about - I mean:

If it is configured to listen for jobs in the "default" queue like so:

```elixir
# confix.exs
config: Exq, queues: ["default"]
```

It should let alone jobs in any other queue.

I'll test this approach and get back with results 👍

**Comment by joaodiogocosta** [comment]
Yep, my last comment seems to make sense ✅

By changing the configuration to include the queue in question:

```elixir
# config.exs
config Exq, queues: ["default", "resource_saver"]
```

And starting `iex -S mix`, I can immediately see jobs starting to be processed by `Exq`:

```shell
21:37:43.637 [info]  Elixir.ResourceSaverJob[63d87388-1d10-4850-9daa-336d1b7d349c] start
```

Which doesn't happen when `"resource_saver"` is not part of the configuration, as intended.

I'm closing the issue 👍
