### ISSUE TITLE
new release for Redix >= 0.8.1?

### ISSUE THREAD

**Issue by bgentry** [akira/exq#357]
#345 upgraded Exq to support and require Redix >= 0.8.1, but this has not been released with a new tagged version of Exq yet. I didn't see any open issues that appeared to be blockers for this. If there aren't any, could you release a new version of Exq?

I'm stuck in a bit of a dependency mess trying to upgrade [exq_ui](https://github.com/akira/exq_ui) and use [exq_scheduler](https://github.com/activesphere/exq-scheduler) along with phoenix_pubsub_redis, but I can't get the Redix versions to agree. I'm planning to PR the upgrades to exq_ui, but didn't want to make it point at `master` here.

Thanks as always for maintaining! :v:

**Comment by akira** [comment]
Hi Blake,

Sure I will do a new release as soon as I get a chance! (I’ve been a bit
busy and hadn’t had much extra time).  Thanks for the help!

**Comment by akira** [comment]
@bgentry I just released this, thank for followup.

**Comment by bgentry** [comment]
@akira awesome, thank you! FYI it looks like the release tag didn't make it up to GitHub

**Comment by akira** [comment]
Thanks, was just looking at that part now 👍
