### ISSUE TITLE
Will this exq support Broadway?

### ISSUE THREAD

**Issue by imVinayPandya** [akira/exq#371]
**This is may be a Proposal**

i have seen that Jose Valim has annouced new elixir module specially for jobs, it has several advantages, for example Back-pressure, Batching, Graceful shutdown(i like this one).

Is there any way that we can use **Exq** with **Broadway**. i think this will be great combination.

i don't know this is valid or not, just curious about this thought.

**Comment by ananthakumaran** [comment]
I don't see how both would work. I am going to close the issue, as this is not actionable. Feel free to re-open if anybody has any concrete proposals.
