### ISSUE TITLE
Outdated info about elixir version in README

### ISSUE THREAD

**Issue by nicktime** [akira/exq#372]
It is stated that "[0.13.2] version requires Elixir 1.3" but really 
```
$ mix test
==> exq
warning: the dependency :exq requires Elixir "~> 1.6" but you are running on v1.5.3
```

**Comment by ananthakumaran** [comment]
readme needs to be updated. mix.exs file is correct. This is because of the dependency on redix which requires `~> 1.6`

**Comment by ananthakumaran** [comment]
This is fixed now.

**Comment by nicktime** [comment]
Thanks!
