### ISSUE TITLE
Performance issue when using realtime stats (with ExqUI)

### ISSUE THREAD

**Issue by neslinesli93** [akira/exq#383]
Hi,
I've recently been hit by some performance issues while using this library. In particular, when visualizing failed tasks, my redis cluster's CPU usage has gone to 100% for a few seconds.

It seems like the reason lies in the way ExQ implements the API for fetching failed tasks, as it can be seen [here](https://github.com/akira/exq/blob/c1caff8052c5176b716715a8bf813d6e87d98f37/lib/exq/redis/job_stat.ex#L123).

As stated inside Redis docs, the `KEYS` command should be avoided when possible, and instead use `SCAN`, which is cursored and doesn't block the whole instance while it's executing.

Thanks for your time!

**Comment by ananthakumaran** [comment]
Closing this as the related PR has been merged
