### ISSUE TITLE
exq_ui can't connect to remote redis server

### ISSUE THREAD

**Issue by cosmos-sajal** [akira/exq#385]
exq_ui runs perfectly on localhost redis, and runs perfectly on staging machine.
But when I try to deploy it on production machine, and tries to connect to remote redis server, it is not able to connect.

This gives the following error -
`{:info, ["Application ", "exq_ui", " exited: " | "exited in: ExqUi.start(:normal, [])\n    ** (EXIT) exited in: GenServer.call(ExqUi.Api, :queue_size, 5000)\n        ** (EXIT) time out"], {{2019, 8, 5}, {13, 14, 43, 992}}, [module: :application_controller, function: "info_exited/3", file: "application_controller.erl", line: 1941]}
Aug 05 13:14:45 ip-192-168-21-71 trafi[13817]: {"Kernel pid terminated",application_controller,"{application_start_failure,exq_ui,{bad_return,{{'Elixir.ExqUi',start,[normal,[]]},{'EXIT',{timeout,{'Elixir.GenServer',call,['Elixir.ExqUi.Api',queue_size,5000]}}}}}}"}`

Following is my config -

```
config :exq,
  name: Exq,
  host: "<redis_host>",
   port: 6979,
  password: "<password>",
  namespace: "exq",
  concurrency: 20,
  queues: [<queues>],
  poll_timeout: 50,
  scheduler_poll_timeout: 200,
  scheduler_enable: true,
  max_retries: 0,
  shutdown_timeout: 5000,
  start_on_application: false

config :exq_ui,
  web_port: 4040,
  web_namespace: "",
  server: true
```

Can someone please help?

PS: I am running my redis on **6979** port on my remote redis

**Comment by cosmos-sajal** [comment]
@akira Can you please help, I am really stuck here.
Not able to put my service on production.

**Comment by akira** [comment]
@cosmos-sajal Can you try connecting to Redis from the server that exq is running from? I am assuming you've updated your configs also to have the correct server information: 

https://github.com/akira/exq/blob/master/config/config.exs#L7

**Comment by ananthakumaran** [comment]
Closing due inactivity.
