### ISSUE TITLE
[DigitalOcean] Issue connecting to TLS/SSL (rediss://...) redis instance

### ISSUE THREAD

**Issue by antonioparisi** [akira/exq#389]
Hi there,

any news on supporting TLS/SSL (rediss://...) option to connect to redis instance?
DigitalOcean out of box uses TLS/SSL only.

Regards,
Antonio

**Comment by ananthakumaran** [comment]
Exq uses [Redix](https://github.com/whatyouhide/redix) library, which already seem to support [ssl](https://hexdocs.pm/redix/Redix.html#module-ssl). You can check [sentinel](https://github.com/akira/exq#sentinel) documentation for how to pass custom options.
