### ISSUE TITLE
[Enhancement] Dynamic subscribe / unsubscribe from queues

### ISSUE THREAD

**Issue by akira** [akira/exq#39]
Provide way to modify queue subscriptions dynamically once Exq is started via subscribe(queue), unsubscribe(queue) calls.

**Comment by dl103** [comment]
Hi guys, I would love to try my hand in contributing to Exq and was looking at this enhancement. If I am understanding this issue correctly, will there need to be two params for subscribe--name and concurrency limit?

**Comment by akira** [comment]
@dl103 great, would welcome any PRs.  It would be two params for subscribe, name and concurrency limit (perhaps second one is optional and uses default if not supplied). Would be helpful to also have some integration tests as well for this feature if possible. Let me know if you run into any roadblocks!

**Comment by akira** [comment]
Closed by #104
