### ISSUE TITLE
GenStage Producer?

### ISSUE THREAD

**Issue by tpendragon** [akira/exq#398]
I've been looking at libraries to do some background data processing given that we have a suite of Rails applications as well and came across ExQ. It looks great! However, we were also looking into Broadway and I wonder if there are any plans to ship the Redis message communication/serialization layer here as a GenStage producer?

**Comment by ananthakumaran** [comment]
Broadway comes with its own concepts like processors and batchers which replaces the worker concept used in Exq/Sidekiq. I think it would be nice to have a broadway producer that utilizes redis list or stream. But also I feel Exq is not the place to add it. It would complicate the Exq api and those who want to use it with broadway would also get confused about what functionality would work with broadway and what would not work.
