### ISSUE TITLE
Can't use standalone mode

### ISSUE THREAD

**Issue by ZastrixArundell** [akira/exq#399]
I tried to run Exq in standalone mode: `mix exq.run` under these settings in `dev.exs`
```
config :exq,
  name: Exq,
  host: "192.168.1.159",
  port: 6379,
  namespace: "exq",
  concurrency: 500,
  queues: ["email"]
```

And I kept getting errors:

```
** (EXIT from #PID<0.91.0>) shutdown: failed to start child: Exq.Manager.Server
    ** (EXIT) an exception was raised:
        ** (RuntimeError)


====================================================================================================
ERROR! Could not connect to Redis!

Configuration passed in: [host: "192.168.1.159", port: 6379, database: 0, password: nil]
Error: :error
Reason: :badarg

Make sure Redis is running, and your configuration matches Redis settings.
====================================================================================================

            lib/exq/manager/server.ex:393: Exq.Manager.Server.check_redis_connection/1
            lib/exq/manager/server.ex:173: Exq.Manager.Server.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

When I set in `dev.exs` that Exq should run in enqueuer mode but I was only able to queue tasks without actually running them. 

Is there a way for me to run Exq in standalone mode to perform tasks and for the phoenix app to run Exq in enqueue mode just so it can queue tasks. 

Note:

I am trying to use Heroku and use my Phoenix application via a Web and the Exq application via a worker so my web thread isn't halted for multiple Redis tasks.

**Comment by kxkannan** [comment]
I would love to know how to run Exq in standalone mode also.

**Comment by ananthakumaran** [comment]
I have updated the readme about how to run exq in different modes. As for the error, it looks like redis config was wrong.
