### ISSUE TITLE
my own Middleware

### ISSUE THREAD

**Issue by ehayun** [akira/exq#400]
I want to start/stop/pause/continue a queue
=======================================
I understand that I have to write my own middleware.
My problem is what should I return if I want to pause the queue
I see that logger:before_work returns a pipleline. what should I return in order to pause the queue (I want that the job will stay in the queue of latter)

I can't find any documentation on that

**Comment by ananthakumaran** [comment]
check if [subscribe/unsubscribe](https://github.com/akira/exq#dynamic-queue-subscriptions) fits your use case. Middleware is mostly used to do something around job life cycle

**Comment by ehayun** [comment]
So, if I unsubscribe from the queue it will stop working and the jobs in it will wait for latter?
If so, this is a great news for me

**Comment by ananthakumaran** [comment]
Yes, it will stop picking up new jobs from the queue. The jobs that were running will not get affected.
