### ISSUE TITLE
Is Exq Mock Deprecated?

### ISSUE THREAD

**Issue by weewey** [akira/exq#403]
Following the testing instructions, I run into issue with 
`Exq.Mock.start_link(mode: :redis)`

`** (UndefinedFunctionError) function Exq.Mock.start_link/1 is undefined (module Exq.Mock is not available)`

I noticed that I couldn't find the Exq.Mock file in the latest 0.134 version of Exq. However I could still see it in the source code of the repo.

**Comment by ananthakumaran** [comment]
The PR just got merged recently and still not released. You could use the master branch or wait for the release.

**Comment by akira** [comment]
I haven't gotten a chance to release the update yet - as I'm on holiday and don't have my personal laptop with me. It should be done after Dec 30th.

**Comment by jocko-wowza** [comment]
So the last comment was in December, but I'm getting the exact same error.  Is it deprecated?  How do I write tests for Exq jobs?
