### ISSUE TITLE
Problems with Jason.encode!

### ISSUE THREAD

**Issue by tfantina** [akira/exq#404]
Reporting just to see if anyone else has encountered this.  We recently upgraded to Erlang 22.2 and bumped several dependencies up.  Now when trying to create a job I get this error: 
```
Request: POST /path
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Jason.encode!/1 is undefined (module Jason is not available)
        Jason.encode!(%{[our json data]})
        (exq) lib/exq/redis/job_queue.ex:447: Exq.Redis.JobQueue.to_job_serialized/5
        (exq) lib/exq/redis/job_queue.ex:22: Exq.Redis.JobQueue.enqueue/6
```
Tried `mix deps.get` and `mix compile` and could not resolve it.  Explicitly requiring `{:jason, "~> 1.1.2"}` in mix.exs fixes the issue.

Not 100% sure if this an Exq thing but I was wondering if anyone else encountered this/if they do requiring Jason may fix it.

**Comment by ananthakumaran** [comment]
We made json library configurable on `0.13.1`. The default library is jason, but it's marked as optional dependency (so you can use poison if desired). Yes adding jason to mix.exs is the right way to fix the issue.
