### ISSUE TITLE
add optional retries_exhausted() callback in worker module

### ISSUE THREAD

**Issue by ericdude4** [akira/exq#406]
I am really enjoying this package, and am currently using it to manage jobs in our API. 

Our API allows 3rd party applications to subscribe to Webhooks from our API. So far, Exq has been perfect for this job, with its automatic retries, max retries, and exponential backoff, etc.

It would be very useful, and I think also appropriate for this package, that a [worker module](https://github.com/akira/exq#creating-workers) be able to implement an optional `retries_exhausted()` callback. For my specific example with the Webhook worker, this would allow my API to send a notification email to the 3rd party application owner notifying them that their webhook subscription has been automatically unsubscribed.

Do you think this is worth implementing? It would be nice to be able to handle this inside of the worker module on a worker-by-worker basis rather than in a series of Middlewares. I would be happy to have a crack at a PR

**Comment by ananthakumaran** [comment]
> It would be nice to be able to handle this inside of the worker module on a worker-by-worker basis rather than in a series of Middlewares.

Could you explain why you prefer not to use middleware for this case? We have a similar use case called DeadJobNotification and we implement it via middleware and it works well so far. Could you list down the pros and cons of middleware vs optional callback

**Comment by ericdude4** [comment]
@ananthakumaran I wrote these pros and cons with error handling in mind, but that is the optional callback that I am requesting so it's only appropriate :) 

### Optional Callback
#### Pros:
- Great for one-off error handlers which apply to a single worker definition.
- Keep the error handling logic in the same place as the worker code which it is related to.
  - The error handler for one worker can be completely different from another.
- Embrace optional callbacks! There are plenty more that could be added
  - For example, `job_failed()`?

#### Cons:
- Not great when you want to build a single error handler that handles errors for all the worker modules in the server.
  - But this is why Middleware is still very valuable :)

### Middleware
#### Pros:
- Great for catch-all handlers which apply to every worker in the server.

#### Cons:
- Not great for specific implementations which apply to only a single worker module, and not others.
- Puts the error handler thats meant for a single worker module in the pipeline for all worker modules.
  - You could create a Middleware that uses pattern matching to run the correct callback based on the worker module, but this would get bloated very quickly.

**Comment by ananthakumaran** [comment]
I understand the benefit of keeping the error handling logic in the same place. Middleware is flexible enough to build your own lifecycle hooks. For example, the below middleware would call the optional `on_dead` callback whenever a job is dead.

```elixir
defmodule DeadCallback do
  @behaviour Exq.Middleware.Behaviour

  def before_work(pipeline) do
    pipeline
  end

  def after_processed_work(pipeline) do
    pipeline
  end

  def after_failed_work(pipeline) do
    worker_module = pipeline.assigns.worker_module
    if dead?(pipeline.assigns.job) && function_exported?(worker_module, :on_dead, 0) do
      apply(worker_module, :on_dead, [])
    end

    pipeline
  end

  defp dead?(%{retry: true} = job) do
    dead?(job, Exq.Support.Config.get(:max_retries))
  end

  defp dead?(%{retry: retry} = job) when is_integer(retry) do
    dead?(job, retry)
  end

  defp dead?(job) do
    dead?(job, 0)
  end

  defp dead?(job, max_retries) do
    retry_count = (job.retry_count || 0) + 1
    retry_count > max_retries
  end
end
```

**Comment by ericdude4** [comment]
@ananthakumaran Thank you for your help and considering my request. I will use this Middleware
