### ISSUE TITLE
Process data type API compatibility with Sidekiq

### ISSUE THREAD

**Issue by deepfryed** [akira/exq#407]
It appears that sidekiq `processes` are stored as a list of keys, each of which references a hash with information about the process. 

Exq treats `processes` as a list of serialized JSON. Is this on purpose or do we expect Exq API to be compatible with Sidekiq ?

https://github.com/akira/exq/blob/master/lib/exq/redis/job_stat.ex#L83
https://github.com/mperham/sidekiq/blame/master/lib/sidekiq/api.rb#L766-L771

Thanks

**Comment by ananthakumaran** [comment]
There is an open PR to fix the issue https://github.com/akira/exq/pull/289#issuecomment-419767005

**Comment by deepfryed** [comment]
looks like this is fixed, closing
