### ISSUE TITLE
Setting the minimal time of when jobs should be re-scheduled in the retry queue.

### ISSUE THREAD

**Issue by ZastrixArundell** [akira/exq#409]
Currently when a job fails and is been put in the retry queue, it is being ran around a minute after said fail. Give-or-take 20 seconds. Now in a project I am working on, it would be ideal to be scheduled to be ran more after that, like a couple of minutes and/or hours. I tried looking at the configuration and had not seen anything functioning as the period of when jobs are re-shceduled in the queue after a fail. 

I know that I could make a work-around by encasing everything in a `try` statement and manually re-enqueue in 5 minutes, but I won't be able to _natively_ keep track of how many times a specific job has been failed. 

So what a I asking is, is it possible to add a setting under the configuration for the default minimum delay to re-enqueue a failed job? Let's say I put a delay of 5 minutes, it would then re-enqueue in 5 minutes + the random time generated by Exq.

**Comment by ananthakumaran** [comment]
@ZastrixArundell it's actually configurable https://github.com/akira/exq/pull/241, just that not documented well

**Comment by ZastrixArundell** [comment]
@ananthakumaran Oh awesome! but it's not working that much. I saw in the PR you mentioned that it uses [this file](https://github.com/akira/exq/blob/master/lib/exq/support/config.ex) for configuration. When I try to use the `backoff` key in my settings and create an invalid job, it doesn't go to the retry queue but rather directly to the failed one. When I remove the `backoff` key, it does everything normal.
