### ISSUE TITLE
Set the amount of max retries dynamically

### ISSUE THREAD

**Issue by ZastrixArundell** [akira/exq#410]
Is there a way to set the amount of max retries dynamically? Similar to how backoff is used (here's the closed issue regarding that https://github.com/akira/exq/issues/409), can the retry count be implemented that way as well, or must it be a hard-fixed value in the config? (would be awesome if it called `run/1` or something similar to how backoff is used so I can add additional logic for dynamic values).

**Comment by ananthakumaran** [comment]
max_retries option can be specified on the enqueue call. I am assuming you want to update based on the kind the error it throws? This method is not officially documented but it works and we use it in prod. Place a custom middleware before Exq.Middleware.Job

```elixir
  middleware: [
    Exq.Middleware.Stats,
    Foo.Middleware.Retry,
    Exq.Middleware.Job,
    Exq.Middleware.Manager,
     ...
  ]
```
Just update the retry key value

```elixir
defmodule Foo.Middleware.Retry do
  @behaviour Exq.Middleware.Behaviour
  alias Exq.Middleware.Pipeline
  import Pipeline

  def before_work(pipeline) do
    pipeline
  end

  def after_processed_work(pipeline) do
    pipeline
  end

  def after_failed_work(pipeline) do
    retry = compute_new_retry(pipeline.assigns.error)
    pipeline |> assign(:job, %{pipeline.assigns.job | retry: retry})
  end
end
```

**Comment by ZastrixArundell** [comment]
Awesome, worked exactly as needed!
