### ISSUE TITLE
Exq GenServer timesouts on a big amount of jobs.

### ISSUE THREAD

**Issue by zastrixarundell** [akira/exq#411]
When I have around 40K jobs in Redis, my application starts to have some issues. When calling `Exq.Api.jobs/2` the GenServer times out and my Phoenix application doesn't even work on some pages that way. Plus the ExqUI crashes when I try to open it on such a count of jobs. I don't think I have un-optimized Exq per se. I'm using a fresh install of Redis (no configuration after I installed the base app) and using Exq with these settings:
```
config :exq,
  host: "localhost",
  port: 6379,
  namespace: "exq:#{Mix.env}",
  concurrency: :infinite,
  queues: ["exq"],
  backoff: Foo.Exq.Backoff,
  start_on_application: false
```

**Comment by ananthakumaran** [comment]
Looks like ExqUI doesn't have proper pagination for jobs page. We use sidekiq ui which works without issue. This issue should be moved to https://github.com/akira/exq_ui repo.

**Comment by ZastrixArundell** [comment]
I just gave ExqUI as an example that it doesn't work as well. I can't either call `Exq.Api.Job/2` as that function itself times out on a large amount of jobs. Is there a way to get elements from index A to index B as that would fix/let me bypass the issue?

**Comment by ananthakumaran** [comment]
I actually don't think there is any api available in Exq as of now. BTW, why do you want to get the jobs?

**Comment by ZastrixArundell** [comment]
I'm adding a functionality which allows you to check the arguments you wrote in a job, which means getting the data from the queue and displaying it. I only need to show around 10 jobs per page, so loading all 40K via `Exq.Api.Jobs/2` is an overkill.

**Comment by ananthakumaran** [comment]
The only way to do this now is to get the data directly from redis. Note that a job will move to different key/datastructure depends on what state it is in (scheduled for retry, in queue, running). Also, the data in redis is not searchable other than scanning all the jobs. We usually store the job info in an external data store and update job status via middleware.
