### ISSUE TITLE
Calling Exq.worker_job() with Exq.Mock in :fake mode raises ArgumentError

### ISSUE THREAD

**Issue by JamesFerguson** [akira/exq#418]
I just wanted to log the current job_id but calling `Exq.worker_job()` when Exq.Mock was setup with this in my test.exs:
```
config :exq,
  queue_adapter: Exq.Adapters.Queue.Mock
```
resulted in this test failure:
```
     ** (ArgumentError) argument error
     code: assert :ok == SessionWorker.perform(@canonical_student_id, @product, @task)
     stacktrace:
       (stdlib 3.12.1) :ets.lookup_element(Exq.Worker.Metadata, #PID<0.658.0>, 3)
       (exq 0.13.5) lib/exq/worker/metadata.ex:20: Exq.Worker.Metadata.lookup/2
       (tracker 0.1.0) lib/tracker/workers/session_worker.ex:76: Tracker.Workers.SessionWorker.schedule_rollup!/1
       test/workers/session_worker_test.exs:57: (test)
```
the relevant method is:
```
  defp schedule_rollup!({:ok, canonical_student_id: canonical_student_id, product: product}) do
    case Exq.enqueue_in(Exq, exq_queue(), @timeout, Tracker.Workers.RollupWorker, [canonical_student_id, product]) do
      {:ok, enqueued_job_id} ->
        %Exq.Support.Job{jid: current_job_id} = Exq.worker_job()
        key = RedisSessionRecord.build_key(canonical_student_id, product)
        Logger.info("[#{key}] Session worker (#{current_job_id}) queued a rollup worker (#{enqueued_job_id}).")

        :ok

      {:error, message} ->
        raise "Could not enqueue rollup worker, error: #{message}"
    end
  end
```
I've worked around this by defining a module variable just to call worker_job() against:
```
  @worker_info_source Application.get_env(:tracker, :worker_info_source, Exq)
```
and replacing the default Exq in test.exs with a mock that returns `%Exq.Support.Job{jid: "dummy-string"}`. But it seems like a bug that I need to do that.

**Comment by ananthakumaran** [comment]
`Exq.worker_job()` can only be called from inside a worker (like the example in the README). I don't know if that's the case here as I can't see the full code. Also, fake mode just stubs the enqueue function and the job enqueued during tests will never get executed.

**Comment by JamesFerguson** [comment]
Thanks.

This was a call from inside a worker. But, yeah, okay makes sense I have to mock `Exq.worker_job()` myself.
