### ISSUE TITLE
How to configure a worker at runtime?

### ISSUE THREAD

**Issue by drmartinberger** [akira/exq#445]
What is the intended and best way to configure a **worker** at **runtime**?

```elixir
defmodule MyWorker do
  def perform do
    IO.puts "Do something with the following runtime parameter #{my_runtime_param}..."
  end
end
```

Thank you in advance for giving me a hint!

**Comment by ananthakumaran** [comment]
I am assuming you want to pass a param while enqueuing the job? refer https://github.com/akira/exq#creating-workers for samples

**Comment by drmartinberger** [comment]
No, that would be fallback solution.
The runtime-config is not really a job-specific argument but runtime-specific parameter to connect to other applications.

Let me give you more context: I have a setup of multiple subsequent workers that connect to individual exq-external applications (REST API, Database, Event Bus and such like) all requiring individual connectivity parameters (only known at runtime, not compile-time). Of course I can transfer the runtime-config of the multiple external applications via a perform-argument like this:

```elixir
defmodule Worker1 do
  def perform(configs = %{app1: config1, app2: _config2, ..., app_n: _config_n}) do
    # Do something and call app1 with config1
    # ...
    Exq.enqueue(Exq, queue_worker_2, Worker2, configs)
  end
end

defmodule Worker2 do
  def perform(configs = %{app1: _config1, app2: config2, ..., app_n: _config_n}) do
    # Do something and call app2 with config2
    # ...
    Exq.enqueue(Exq, queue_worker_3, Worker3, configs)
  end
end

# ... a few more workers

defmodule WorkerN-1 do
  def perform(configs = %{app1: _config1, app2: _config2, ..., app_n: _config_n}) do
    # Do something and call app_n-1 with config_n-1
   # ...
   Exq.enqueue(Exq, queue_worker_n, WorkerN, configs)
  end
end

defmodule WorkerN do
  def perform(configs = %{app1: _config1, app2: _config2, ..., app_n: config_n}) do
    # Do something and call app_n with config_n
    # ...
  end
end
```

This approach seems sub-optimal since the runtime-config of all external applications need to be looped through all workers (including the Redis database).

Any better ideas are very welcome!

**Comment by ananthakumaran** [comment]
Not sure I understand what you mean by runtime config. Exq workers are just plain elixir modules. If the config is not job specific, you could just use the same approach used elsewhere like Application.get_env, etc

**Comment by drmartinberger** [comment]
Hi @ananthakumaran, thank you!

I think you brought me on the right track.
I tried with Application.get_env before, but as module attribute outside of a function, where [Application.get_env is evaluated at compile time](https://hexdocs.pm/elixir/1.12/Application.html#module-compile-time-environment).
I will test with Application.get_env within the perform-function of the module for the worker.

Cheers!
