### ISSUE TITLE
Exq vs Oban?

### ISSUE THREAD

**Issue by chavenor** [akira/exq#465]
I'm new to the Elixir world and I can't understand why someone wouldn't go with a Redis backend for a job queuing systems vs Postgres, yet everywhere I turn everyone is raving about Oban - what am I missing?

Why Oban over Exq?

**Comment by ananthakumaran** [comment]
You can check the [advantages over other tools](https://github.com/sorentwo/oban#advantages-over-other-tools) section. You might get biased answers here, elixirforum might be a better place for these type of questions.
