### ISSUE TITLE
Redis 6.0 ACL is supported ?

### ISSUE THREAD

**Issue by succoDiPompelmo** [akira/exq#467]
Hi,

I was looking to see if the library supported the new Redis 6 feature of authentication through ACL system (https://redis.io/commands/auth). I searched through the directory and it seems that the AUTH command has not been implemente. Am i wrong ?

**Comment by ananthakumaran** [comment]
I haven't tested it out, but it should work. Exq has a config option called [redis_options](https://github.com/akira/exq#sentinel) which is passed directly to the underlying library Redix. Redix supports [username/password](https://hexdocs.pm/redix/Redix.html#start_link/1-redis-options) option.

```
config :exq
  redis_options: [
    username: "username"
    password: "secret",
    timeout: 5000,
    name: Exq.Redis.Client
  ]
```
