### ISSUE TITLE
Dynamic subscription enqueued workers never run

### ISSUE THREAD

**Issue by ericdude4** [akira/exq#468]
When creating dynamic queue subscriptions, enqueued workers to that queue just sit in the list of enqueued jobs and are never actually run.

```
iex(1)> Exq.subscriptions Exq
{:ok, ["dynamic-1", "default"]}

iex(2)> Exq.Api.queue_size Exq.Api
{:ok, [ {"dynamic-1", 0} ]}

iex(3)> Exq.enqueue(Exq, "dynamic-1", TestWorker, [:foo, :bar])
{:ok, "4df59aad-2633-4d37-9636-8724e0c64365"}

iex(4)> Exq.Api.queue_size Exq.Api
{:ok, [ {"dynamic-1", 1} ]}
```

The job created in `iex(3)` never runs, no matter how many workers are enqueued to this queue. However, once I run `Exq.subscribe Exq, "dynamic-1"` again (now appears twice in `Exq.subscriptions Exq`), all of the enqueued workers begin to run for that queue. 

One thing to note is that I am subscribing to these dynamic queues at application startup. Maybe I need to wait for some event before Exq is ready before I call `Exq.subscribe/2` for all my dynamic queues?

**Comment by ananthakumaran** [comment]
Could you share a minimal reproducible script?. I tried to reproduce the issue by placing the subscribe call inside the Application start callback, but it does work correctly and jobs are picked up.

**Comment by ericdude4** [comment]
@ananthakumaran Thanks for trying! I figured it out. I had `middleware: [Exq.Middleware.Job]` in my config which wasn't reporting any jobs as complete. So after reaching the concurrency limit with incomplete jobs, the newly enqueued jobs would just get added to the queue.
