### ISSUE TITLE
expected :timeout to be an integer of :infinity, got: nil

### ISSUE THREAD

**Issue by fekle** [akira/exq#474]
Hi there,

I am in the process of trying `exq` and it looks very promising so far - however I stumbled upon an issue which prevents starting `exq` on application startup. 

I am getting the following Error:

```iex
** (Mix) Could not start application __REDACTED__: __REDACTED__.Application.start(:normal, []) returned an error: shutdown: failed to start child: Exq
    ** (EXIT) shutdown: failed to start child: Exq.Manager.Server
        ** (EXIT) an exception was raised:
            ** (RuntimeError) 


====================================================================================================
ERROR! Could not connect to Redis!

Configuration passed in: [[host: "localhost", port: __REDACTED__, database: 0, password: nil, name: Exq.Redis.Client, socket_opts: []]]
Error: :error
Reason: %ArgumentError{message: "expected :timeout to be an integer of :infinity, got: nil"}

Make sure Redis is running, and your configuration matches Redis settings.
====================================================================================================

                (exq 0.16.2) lib/exq/manager/server.ex:437: Exq.Manager.Server.check_redis_connection/1
                (exq 0.16.2) lib/exq/manager/server.ex:179: Exq.Manager.Server.init/1
                (stdlib 4.1.1) gen_server.erl:851: :gen_server.init_it/2
                (stdlib 4.1.1) gen_server.erl:814: :gen_server.init_it/6
                (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

My Redis instance is up and running and reachable, the issue seems to be related to Exq's usage of Redix.
I already tried both starting `exq` as an OTP application as well as setting `start_on_application: false` and starting `exq` in my supervisor tree, the issue remains the same.

I also tried adding `timeout` to the `redis_options` parameter in  Exq's options.

Elixir Version: Erlang/OTP 25 Elixir 1.14.0 (compiled with Erlang/OTP 25)
Exq Version: 0.16.2
Redix Version: 1.2.0
OS: Debian 11 & macOS 13

Is anyone else having this issue?

**Comment by akana** [comment]
Hi! I also have the exactly the same error as her. My project dependency is also the same as her.

**Comment by ananthakumaran** [comment]
A new redix version got released 2 weeks ago, it might be due to that.
Could you pin your redix version to 1.1.x and check if it solves the
problem? I will look at the issue soon.

**Comment by ananthakumaran** [comment]
The fix will be merged to master soon. For now, you can workaround the issue using the below config

```elixir
config :exq,
  redis_timeout: 5000
```

**Comment by fekle** [comment]
@ananthakumaran Thank you so much, this fixes the issue! 
And yes, the problem seems to be with `redix 1.2.x`.

Have a nice weekend!

**Comment by akana** [comment]
@ananthakumaran Thank you very much. the workaround solve my problem.
