### ISSUE TITLE
Feature Request: enqueue a batch of jobs atomically

### ISSUE THREAD

**Issue by meysius** [akira/exq#482]
# Usecase
In our application we need to send ~2000 events on our message broker all at once (or not at all, a.k.a atomically). So we need to submit many jobs all at once but it cannot be a single job so we can process them concurrently.

# Proposal
This can be achieved by using [Redis Transactions](https://redis.io/docs/manual/transactions/)

# Proposed API
```elixir
jobs = [
  [job_1_queue, job_1_worker, job_1_args],
  [job_2_queue, job_2_worker, job_2_args],
  [job_3_queue, job_3_worker, job_3_args],
  ...
]
{:ok, ack} = Exq.Enqueuer.enqueue_all(Exq.Enqueuer, jobs)
```

I will be happy to work on this myself and put a PR up, just wanted to make sure this feature is compatible with all the existing features or if there is anything I need to know before starting to work on this.

**Comment by ananthakumaran** [comment]
Feature wise, this is a nice addition. I would suggest including options. It's ok to not support all the options supported by enqueue in the first cut, but we should include options, so support can be added in the future.

> [job_1_queue, job_1_worker, job_1_args, job_1_options],

> I will be happy to work on this myself and put a PR up

Thanks.

**Comment by ericdude4** [comment]
@ananthakumaran can you release a new version to hex with this feature?

**Comment by akira** [comment]
@ericdude4 just released a new version 👍
