### ISSUE TITLE
[Enhancement] Ability to limit the concurrency of a specific queue.

### ISSUE THREAD

**Issue by j-mcnally** [akira/exq#5]
Would be nice for tasks such as video encoding to be able to to only run one task in a specific queue at a time.

We could allow queues to be specified in the for [{"Default", 50}, {"Encoding", 1}]

Since the workers per queue would be tracked on a per instance basis, we can keep track of the number of running tasks in ETS rather than redis.

**Comment by akira** [comment]
Closed by #67
