### ISSUE TITLE
Redis auth support

### ISSUE THREAD

**Issue by akira** [akira/exq#53]

**Comment by optikfluffel** [comment]
What's the status on this one?

**Comment by akira** [comment]
I haven't had a chance to look at this - it's open to take a crack at. If you need this quick, I can add an extra param for the auth for now. I probably won't get a chance to look at the URL based approach until this/next weekend unless you get to it first.

**Comment by optikfluffel** [comment]
I just saw that [Redis only supports authentication via `password`](http://redis.io/commands/AUTH) (no user), so the URI should be something more like `redis://:password@host:port/database`. Also [eredis support password authentication already](https://github.com/wooga/eredis/blob/4480c062ab4ce9b45a258fc3f793e3bc75ac0a73/README.md#commands) so we'd just have to pass that through.

**Comment by akira** [comment]
@optikfluffel I just realized that Redis AUTH is already supported as an option, it is 'password' on the config params, I updated README.  Closing this, and added #71.
