### ISSUE TITLE
RFC: Middleware support

### ISSUE THREAD

**Issue by j-mcnally** [akira/exq#63]
I think we have a pretty good base for a lot of use cases.

Personally I have branches that add specific functionality that I want but might not be perfect for everyone.

I would like to explore some sort of contrib libraries to add functionality without maintaining additional forks or shoe horning them into main line.

This proposal is to add hooks into exq mainline that would allow for 3rd party libraries to add extensions.

I'd love thoughts related to how we can build a system to allow middleware similar to what sidekiq supports.

**Comment by akira** [comment]
Agreed, how about doing something similar to Plug / Phoenix pipeline - to define a middleware API and way to configure the middleware chains?

**Comment by akira** [comment]
Would also be ok with a simpler rack like solution for first version if other way is too much work.  I think Sidekiq does this in the processor and runs it through the middleware chain before dispatching the final worker.

**Comment by optikfluffel** [comment]
+1 for something Plug-like

**Comment by akira** [comment]
Provided by #160
