### ISSUE TITLE
Not compatible with Sidekiq when using namespace

### ISSUE THREAD

**Issue by yangweiqi** [akira/exq#81]
Sidekiq key in redis: "queue:queue_name"
Exq key: "namespace:queue:queue_name"

**Comment by akira** [comment]
The idea is that it would be compatible if you use the same namespace in Sidekiq as well:

https://github.com/mperham/sidekiq/wiki/Advanced-Options

With this option set in Sidekiq, it seems to be consistent with this, I'm seeing Sidekiq use:
```
"namespace:queue:queue_name"
```

You also set an empty namespace for Exq, in that case it should work when Sidekiq doesn't not have it set.  

Let me know if that works as expected. 

Thanks!

**Comment by yangweiqi** [comment]
I made a mistake in Sidekiq configuration, you're right. Thank you!

**Comment by akira** [comment]
No problem!
