### ISSUE TITLE
Outdated version of timex causing issues on OSX

### ISSUE THREAD

**Issue by martinstannard** [akira/exq#92]
I've been trying get exq running on OSX Yosemite 10.10.5 and have run into an issue when trying to enqueue a job:

```
iex(7)> {:ok, jid} = Exq.enqueue(:exq, "default", Eventer, []) 
** (exit) exited in: GenServer.call(:exq, {:enqueue, "default", Eventer, []}, 5000)
    ** (EXIT) exited in: :gen_server.call(#PID<0.203.0>, :stop)
        ** (EXIT) no process
    (elixir) lib/gen_server.ex:356: GenServer.call/3
iex(7)> 
21:25:39.328 [error] GenServer :exq_enqueuer terminating
Last message: {:"$gen_cast", {:enqueue, {#PID<0.190.0>, #Reference<0.0.1.4934>}, "default", Eventer, []}}
State: %Exq.Enqueuer.Server.State{namespace: "exq", redis: #PID<0.203.0>, redis_owner: true}
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, "No timezone found for: No timezone found for: AEST"}
        lib/timezone/timezone_dst.ex:20: Timex.Timezone.Dst.is_dst?/1
        lib/dateformat/formatter.ex:139: Timex.DateFormat.Formatters.Formatter.format_token/2
        lib/dateformat/formatters/default.ex:201: Timex.DateFormat.Formatters.DefaultFormatter.do_format/3
        lib/dateformat/formatters/default.ex:194: Timex.DateFormat.Formatters.DefaultFormatter.do_format/3
        lib/dateformat/formatter.ex:36: Timex.DateFormat.Formatters.Formatter.format!/3
        (exq) lib/exq/redis/job_queue.ex:124: Exq.Redis.JobQueue.to_job_json/3
        (exq) lib/exq/redis/job_queue.ex:37: Exq.Redis.JobQueue.enqueue/5
        (exq) lib/exq/enqueuer/server.ex:43: Exq.Enqueuer.Server.handle_cast/2
```

So it seems my timezone is being returned as "AEST" (Australian Eastern Standard Time). This isn't parsable by Timex, so the enqueing fails.

In iex I get these results when using the version of Timex required by exq:

```
iex(5)> Timex.Timezone.Local.lookup
"AEST"
iex(6)> Timex.Timezone.local       
{:error, "No timezone found for: AEST"}
iex(7)> Timex.Timezone.Local.parse_tzfile("/etc/localtime")
{:ok, "AEST"}
```

When I setup a new project with just the latest version of Timex (0.19.5) the timezone seems to work correctly:
```
iex(2)> Timex.Timezone.local
%Timex.TimezoneInfo{abbreviation: "AEST",
 from: {:sunday, {{2015, 4, 5}, {2, 0, 0}}}, full_name: "Australia/Sydney",
 offset_std: 0, offset_utc: 600, until: {:sunday, {{2015, 10, 4}, {2, 0, 0}}}}
iex(3)> Timex.Timezone.Local.lookup
"Australia/Sydney"
iex(4)> Timex.Timezone.Local.parse_tzfile("/etc/localtime")
{:ok, "AEST"}
```

It seems to me that bumping the version of Timex should resolve the issue above. Thoughts?

**Comment by akira** [comment]
:+1: for upgrading Timex. 

That does seem to fix the issue. I ran the tests, and a few are failing because the performance seems degraded by 3x for that version of Timex. Some further digging is probably needed on that.

**Comment by martinstannard** [comment]
https://github.com/bitwalker/timex/issues/68 documents some performance degradation, which has apparently been addressed - would be good to see what the number are for 0.19.5, and if this is the cause of the issue.

**Comment by sinetris** [comment]
@martinstannard have you added `:tzdata` to the applications in `mix.exs`? Is required for the new Timex

**Comment by akira** [comment]
@martinstannard feel free to use my branch above for now which bumps timex. I briefly looked into the timex issue above, and it doesn't seem like the regression is due to that issue, as the caching seems to work, but not 100% sure. I am currently on vacation at the moment so haven't had time to dig further, but will try to look into it when I get back.

**Comment by martinstannard** [comment]
Thanks @akira - will give that a go - enjoy your break!

**Comment by akira** [comment]
Filed issue in timex:

https://github.com/bitwalker/timex/issues/92

**Comment by akira** [comment]
Merging.  Opened #102 for later exploration.

**Comment by martinstannard** [comment]
Thanks @akira !

**Comment by akira** [comment]
No problem!
