### ISSUE TITLE
OTP application elixir 1.1.1

### ISSUE THREAD

**Issue by triptec** [akira/exq#94]
I'm trying to use exq with elixir 1.1.1

I keep getting this error when I try to start the app

=INFO REPORT==== 6-Oct-2015::06:39:11 ===
    application: logger
    exited: stopped
    type: temporary
Could not start application exq: Exq.start(:normal, []) returned an error: shutdown: failed to start child: Exq.Manager.Server
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in :eredis.start_link/6
            (eredis) src/eredis.erl:48: :eredis.start_link('redis', "6379", 0, [], 100, 5000)
            (exq) lib/exq/manager/server.ex:31: Exq.Manager.Server.init/1
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

mix.exs:

defmodule AW.Mixfile do
  use Mix.Project

  def project do
    [app: :aw,
     version: "0.0.1",
     elixir: "~> 1.0",
     #build_embedded: Mix.env == :prod,
     #start_permanent: Mix.env == :prod,
     escript: [main_module: AW],
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type `mix help compile.app` for more information
  def application do
    [applications: [:logger, :httpoison, :amqp, :postgrex, :exq]]
  end

  # Dependencies can be Hex packages:
  #
  #   {:mydep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:mydep, git: "https://github.com/elixir-lang/mydep.git", tag: "0.1.0"}
  #
  # Type `mix help deps` for more examples and options
  defp deps do
    [
      {:httpoison, "~> 0.7"},
      {:poison, "~> 1.4.0"},
      {:postgrex, "~> 0.8"},
      {:exjsx, "~> 3.2.0"},
      {:amqp, "0.1.1"},
      {:slugger, git: "https://github.com/triptec/slugger.git"},
      {:exq, git: "https://github.com/akira/exq.git", branch: "upgrade_timex"}
    ]
  end
end

**Comment by akira** [comment]
In your config.exs, is```exq->port``` listed as integer or string? I think eredis might be expecting integer while above seems to be listed as string.

**Comment by triptec** [comment]
Yeah, I used System.get_env("REDIS_PORT").

Thanks!
