### ISSUE TITLE
Support for Redis sentinel

### ISSUE THREAD

**Issue by akira** [akira/exq#97]
Add support for Redis Sentinel (http://redis.io/topics/sentinel) which provides HA Redis setup.

**Comment by lpil** [comment]
What prevents Exq from currently working with Redis sentinel?

**Comment by akira** [comment]
@lpil the client would need to handle it, since there is a check before connecting:  
https://redis.io/topics/sentinel-clients

**Comment by akira** [comment]
This is provided by #296
